是否付款=Check and Pay
注意=Attention
大编码=Airlines PNR
去核对=Go to check
退票管理=Refund
联系人姓名=Name
重新输入=Clear
类型=Type
航程=Voyage
证件类型=Identity Type
张=Tickets
客人姓名=Passenger Name
身份证=ID Card
客户名称=Name
收益分析=Profit View
否则无法登机=Or you can't board.
出票时间=Ticketing Time
批量上传=Batch Upload
保险份数=number of insurances
婴儿=Infant
请确认舱位状况=Please confirm the status of the cabin
内容获取=get content
删除=Delete
发送短信=Send SMS
成人=Adult
航班信息=Flight Info
当前=Now
机建燃油=Airport&Fuel Fee
位乘机人=passengers
改期费=Reschedule Fee
每页展示条数列表=Lines per page
未支付=Unpaid
实时数据=Real-time data
国内单程=One Way
保险总计=Insurance Fee
编码内不能存在不同的乘客类型=Only single type of passenger allowed in PNR
正常改期费是保存到税金字段=Normally reschedule fee is saved to tax item
用户数量=Total
出生日期=Birth Date
现有客户=Now there is(are)
抵达=Arrival
每页显示条数下拉列表=Lines per page Drop-list
份=Copies
请准确填写联系人信息=Please fill in the contact information accurately
合计=Total
入库后的=Stocked
军官证=Military ID
历史订单=History
充值记录=Recharge History
取消订单=Cancel
机场=Airport
往返=Roundtrip
期限=Deadline
改期中=Rescheduling
出发日期=Departure date
同步新=Sync New
保险信息=Insurance Info
位以下的数字或字母=digits or letters below
说明=Instruction
预订日期=Booking Date
下级分销分润=Sub-distributor Profit
修改=Edit
审批日期=Approved Date
退票规定=Refund Policy
请确认每个旅客均已输入证件号码=Please confirm that each passenger has entered the ID number
邮寄发票=Mail Receipt
序号=Serial No.
机场税=Airport TAX
应付金额=Total
乘机人数=How many passengers
充值=Add Funds
个航班=flights
乘机人类型=Type
已审核=Audited
最后修改=Lastest Update
填写订单=Order
查询条件=Search Filter
汇总=Sum Up
证件签发地=Place of issue
请确认=Please confirm
终止日期=End Date
退票费率=Refund Rate
已用=Used
已欠款余额=Credit Left
出票中=Ticketing
联系手机=Telephone
请准确填写登记人信息=Please fill in the registration information correctly.
机票须按航班起飞时间顺序使用=Using air tickets in order of flights departure time
新增操作员=Add Operator
备注信息=Note
个=A
已欠款=Debt
台胞证=MTPs
用户=User
开通日期=Since
订票人=Agent
选择客户=Choose Client
共找到符合条件的订单数有=Found
航段=Segment
单位=unit
成交张数=Total Ticket(s)
结算价=Settlement
浏览=Browse
请不要导入已经出票=Cannot import!Already ticketed!
可欠款余额=Credit
修改密码=Confirm
到达=To
下载=Download
个人版=Personal
返佣利率=Commission Rate
姓名=Name(CH)
出票方有权拒绝出票=The drawer has the right to refuse Ticketing.
国际机票预订单=International Ticket Order
请输入支付密码=Please enter Payment Password
自购出票利润=My Profit
销售价=Sale Price
返佣日期=Commission Date
国际机票=International
定期更换您的密码可以让您的账户更加安全=Changing your password regularly can make your account more secure
航空公司=Airline
开通条数=Available Messages
预订=Book
手机号码=Telephone
已支付=Paid
重新查询=Search
退废类型=Refund Type
业务统计=Statistics View
重置=Reset
保险备注=Note
订座记录=Booking Record
同意以上条款=Agree terms above
病退证明=Illness Refund Proof
出发时间=Departure time
起飞时间升序=Earliest time
办理对象=Object
联系电话=Phone
剩余=Left
选择银行=Select a Bank
取票方式=Pickup Way
税费=Tax
请在编码里输入指令授权我们提取编码内容=Please modify PNR to authorize us to extract PNR content.
国内航班查询=Flight（Domestic）
护照有效期=Passport Validity
金额=Amount
按起飞时间从晚到早=Depart Latest
短信=SMS
短信=SMS
列表=List
日期=Date
没有符合条件的记录=Attention:No result(s).
燃油=Fuel Fee
不包括=Exclude
护照证件下拉选择=Passport Document Dropdown selection
订单创建时间=Order Time
请输入新密码=New Password
申请充值人员=Operator
联系信息=Contact info
确定=Yes
常旅客信息=Frequent Flyer information
舱位=Cabin
更多舱位=More
产品名称=Product Name
乘机人类型列表=Passenger type list
提示=Notice
操作时间=Time
修改订单=Modify Order
周岁=Years
乘机人姓名=Name
已改期=Rescheduled
按价格从低到高=Price:Low to High
凭证号=Voucher No.
分销客户列表=Distributor List
编码=Code
查询=Search
假=FALSE
显示共享=More Flight
上一步=Previous
网络电子客票协议=Network e-Ticket agreement
机票=Ticket
项目的=Project's
账户余额=Account Balance
已取消=Canceled
航段组正确=Segment item is correct
折扣率=Discount rate
进行导入=To import
保险=Insurance
保险=Insurance
应退金额=Net Refund
请输入条件查询=Please search by filter
数量=Amount
航班号=Fight No.
按价格从高到低=Price:High to Low
订单号=Order No.
结算总金额=Amount
本部信息=Headquarter Info
充值类型=Method
确定发送=Send
港澳通行证=Passport(HK/Macao)
服务费=Service Fee
带审核=Checking
分销级别=Distributor Tier
航程类型=Type
工作时间=Work Time
订单时间=Order Time
单程=One way
排序方式下拉列表=Sort by Drop-down List
起飞日期=Departure date
航司列表选项=Airlines list
编码不能存在不同的乘客类型=Different passenger types are not allowed in PNR
结算小计=Settlement Subtotal
银行卡网银支付=Online Bank
出票预订单数=Total Ticketing/Booking
分销编码=Distributor Code
酒店=Hotel
酒店=Hotel
客户=Client
航站楼=Terminal
管理员=Administrator
开户日期=Open Date
座位=Seats
请确认新密码=Confirm New Password
排序方式=Sort by
手工录入=Manually Input
支付类型=Payment Methods
返点=Rebate
乘客性别=Gender
天=day(s).
更改支付密码=Change Password
明细=Details
提交=Submit
会员=Member
联系人=Contact
交易类型=Deal Type
所用流量=Flow Used
出票统计=Ticket View
预订电话=Telephone
待出票=Waiting for ticketing
机票税=Ticket Tax
条=branches
各航司=Airlines
分销名称=Distributor Name
小编码=Pre-PNR
注册日期=Register Date
详情请咨询签证办理方=For details, please contact the visa issuer
联系人信息=Contact information
下载报表=Download Report
每页展示信息条数下拉列表=Lines per page dropdown list
确认提交=Submit
重新选择=Clear
查询城市=Search City
出发=From
现有操作员=Total operators
账户信息=Account
订单管理=Orders
备注说明=Note
票证类型=Ticket Type
出票完成=Done
配送机构=Delivered by
请确保=Please make sure
财务=Finance
英文姓名=Name(EN)
欠款额度=Credit limit
请保持支付密码与登录密码不同=Please keep the payment password different from the login password
退票中=Refunding
其他证件=Other
当前分销已使用=This distributor has used
售价=Price
虚假=FALSE
充值额度=Limit
申请日期=Date
预订员=Operator
航司=Airline
到达城市=Arrival City
选择航班=Flight
预付款=Prepayment
国内=Domestic
业务员=Operator
查询航班=Search
请不要修改=Please do not modify
请选择航线=Choose Air Line
航班日期=Flight Date
手机=Telephone
系统自动获取=get automatically
适用类型=Activation Type
订单确认=Confirm
航程类型下拉列表=Voyage type dropdown list
出发城市=Departure City
个被暂停=suspended
确认=Yes
待审核=Checking
国内联程=Multi-Leg
回程=Return
余额=Balance
起降时间=Depart/Arrival time
证件号码=ID No.
发送内容=Text
支付票款=Pay
联系方法=Contact Info
共有=Found
充值申请记录=Recharge history
团队签证无法单独购买机票=Team Visa cannot buy ticket for single
正常=Normal
个符合条件的结果=result(s)
保险金额=Insurance Fee
终止=End
操作员=Operator
资金报表=Funds Report
提示信息=Notification
选择=Choose
改期管理=Reschedule
按起飞时间从早到晚=Depart Earliest
内容真实准确=True and accurate content
新增=New
机场自取=Airport Pickup
证件号码列表=Certificate Number List
乘客类型=Type
请输入旧密码=Old Password
活跃度统计=User Activity
确定提交=Submit
搜索到=Found
总计=Total
电话=Telephone
出票速度=Ticketing Time
已退票=Refunded
项=item
出票比=Ticketing Rate
人数=Number of Passengers
其中有=There is(are)
国内往返=Roundtrip
销售统计=Sales View
待支付=Need to pay
充值金额=Recharge Amount
退废时间=Refund&Void Time
姓=Last Name
费率=Rate
这样才能和=In order to
机票价格升序=Ascending Price
乘客和航段=Passenger and Segment
报表对应=Report Correspond to
起飞=Depart
去程=Depart
订单总数=Total Order
其他支付=Other
申请时间=Apply Date
常旅客分组=Frequent Flyer Group
关闭=Close
票号=Ticket No.
总数=Total
抵达城市=Arrival City
界面小计=Interface Subtotal
总价=Total
银行汇款=Remittance
上传延误=Upload delay
暂停日期=Suspension
乘机人手机=Telephone
密码必须是=Password must be
航空公司下拉列表=Airline dropdown list
全部订单=All
升舱费=Upgrade Fee
选择改期航班=Choose New Flight
航班时间=Flight time
且区分大小写=Case-sensitive
儿童=Child
报表类型=Report Form
允许欠款=Time Limit
获取=Gets
修改登录密码=Change Login Password
证件信息=Identity Info
已分配给下级分销个=Assigned to a subordinate distributor
利润=Profit
未审批=Unapproved
订单编号=Order Number
页=Page
机建=Airport Fee
编号=Number
特别提醒=NOTE
提示内容=Tips
预订成功=Success
已退=Refunded
全部=All
全选=All
审批状态=Status
暂停=Suspended
保额=Sum insured
票面价=Price
外购=Outsourcing
交易大于=More Than
证件签发地下拉选择=Paper issuing location dropdown list
其他费用=Other Fee
不需发票=No invoice
复制=Copy
等待出票=Ticketing
统计方式=Type
符合条件的结果=result(s)
改期手工录入=Reschedule Manually Input
性别=Gender
保险种类=Insurance Type
预订人=Operator
护照=Passport
常用短语=Useful Expressions
其他=Other
乘客=Passenger
详细信息=Details
下一步=Next
操作=Operate
最后访问=Lastest Visit
请输入有效的=Please enter a valid
乘机人=Passenger
位以上=Bit above
航班=Flight
每页=per page
用户名=Username
已拒绝=Denied
百分比=Percent
友情提示=Attention
编辑=Edit
到=To
出票日期=Ticket Date
送票服务=Ticket delivery
或者输入过=or entered
当前状态=Status
内容=Text
查询条件类型下拉选择=Search filter dropdown list
当天直飞最低价=Best Non-Stop
燃油税=Fuel Tax
隐藏佣金和结算价=Hide Profit
旅客组=Passenger Group
温馨提示=Tips
元=Yuan
申请次数=Apply Times
查询条件下拉类型列表=Filter Drop-down list
前台自取=Front Desk Pickup
常旅客=Frequent Flyer
单号=Order NO.
航司手续费=Airline Fee
备注=Note
乘机人信息=Passenger Information
乘客姓名=Passenger Name
女=Female
男=Male
充值申请人=Applied by
票价=Price
代理费=Agent Fee
操作人=Operator
如果您的编码不是我们平台系统订座的=If your PNR is NOT generated by our platform
我已阅读并同意=I have read and agreed
名=First Name
出票方式=Ticketing Mode
第=di
支付密码设置=Payment Password
同步旧=Sync Old
其他产品=Other Product
联系方式=Contact
选择航段=Select Segment
取消密码=Delete Password
订单提交成功=Submitted
取消支付密码=Delete Password
加收的改期费和升舱费保存到票价字段=The rescheduled and upgrade fees are saved to the fare item
国籍=Nationality
状态=Status
标题=Subject
折扣=Discount
已审批=Approved
以免影响正常登机=To avoid boarding failure.
报表下载=Download Report
预付款余额=Balance
成交金额=Ticket Amount
证件有效期=Validity date
数据写入失败=Data Writing Failed
不能输入空格和中文字符=No chinese characters or space
核算项目=Accounting items
您公司没有查询接口的使用权限=Your company does not have permission to query the interface
请检查你输入的登录密码是否正确=Please check that the login password you entered is correct
信用额度明细下载=Credit Details Download
本页小计=Subtotal
状态不能为空=State cannot be empty
位字符=Bit characters
单张婴儿机票价格=Single Infant ticket price
格式错误=Format error
开设下级分销=Open a subordinate distributor
系统功能=Functions
充值明细下载=Recharge details Download
搜索=Search
至=To
注=Note
等待买家付款=Waiting for payment
请输入条件进行查询=Please enter criteria for query.
系统提示=Alert
格式无效=Invalid format
客户变动记录=Distributor Change Log
职务=Title
已开启=Turned On
减一个区间=Subtract an interval
单张儿童机票价格=Single ticket price for children
正在为您查询分销信息=Checking distribution information for you
用户名已存在=User name is already existed
用户名只能是字母或数字的组合=Username can only be a combination of letters or numbers
级分销=Distributor
公司名称=Company
查看操作员修改记录=View operator Modification Records
日期范围=Date Range
预留=Reserved
写入系统=Write system
请至少选择一种适用类型=Please select at least one type
会员变动记录=Member Change record
录入日期=Record Date
批量导入=Bulk Import
选择要上传的文件=Select files to upload
客户代码=Customer Code
密码长度不能小于六位字符=Password length cannot be less than 6 characters
变更记录=Change record
请输入正确的预警授信额度=Please enter the right warning credit limit
修改时间=Update Time
位英文字母和数字的组合=A combination of English letters and numbers
查询交易结果=Check transaction result
联系地址=Address
您的密码已经修改成功=Password has been successfully changed
成功批量上传=Successfully bulk upload
分销操作员代码不能为空=Distribution operator code cannot be null
交易不存在=Deal doesn't exist.
交易失败=Transaction failed
分销操作员=Distributor operators
建议=Recommendations
查询退款结果=Refund result
分销操作员修改成功=Modify Distribution operator successfully
号=hao
如=Example
交易关闭=Transaction is shut down
已关闭=Closed
邮政编码=Zip code
时=Hour
变动=Trace
返现奖励=Rebate Reward
点击这里下载excel模板=Click here to download the Excel template
要修改的客户不存在=The customer to be modified does not exist
分配下级分销帐号数量总共=Total number of sub distributor accounts allocate
用户数量受限制=Limited number of users
预订电话不能为空=Reservation Phone number cannot be empty
错误提示=Error
签注内容=Content
您没有权限=You do not have permission
只支持.xls扩展名的excel文件=Support only .xls excel file
分销客户分销留点修改成功=Modify Distribution agent reserve rate successfully
正在搜索=Searching
总共授权帐号数量=Total number of authorized accounts
客户认证失败=Customer Authentication Failed
有效期=Validity
业务员不能为空=Salesman cannot be empty
身份证号格式不对=The ID number is not in the right format
请输入详细联系地址=Please enter specific address
修改支付密码=Modify Payment Password
请联系支付宝签约人开通交易查询接口功能=Please contact Alipay to open the Transaction query interface function
公司地址=Company Address
请稍候=Please wait.
您必须输入您的密码=You must enter your password
文件后缀不符合要求=File suffix does not meet requirements
请输入用户数量=Please enter the number of users
姓不能为空=Last name cannot be empty
录入时间=Record Time
中心=Center
消费=Consumption
扣款金额=Reduction
生成文件失败=Failed to generate file
所属分销客户=Distribution Customers
增一个区间=Add an interval
区分大小写=Case sensitive
用户数量不能为=The number of users cannot be
易宝无卡支付=Yeepay No card payment
您上传的数据的列数不对=The data you uploaded is not in the correct number of columns
请输入正确的手机号=Please enter the correct telephone number
贵分销总共授权帐号数量=Total authorized account number of your distribution
请选择要批量修改的客户=Please select customers to be modified in bulk
其他设置=Other settings
启用=Enabled
批量修改状态=Bulk modification Status
信用额度调整=Credit limit Adjustment
批量修改成功=Batch modification Successful
已存在=existed
配送=Delivery
订单签注记录=Order Endorsement Record
付款科目=Payment Account
分销操作员添加成功=ADD Distribution operator successfully
终止/暂停=Stop/Suspend
传真号码=Fax
查询结果为支付成功=Successfully done
订单编码=Order code
联动优势无卡支付=UMPAY no card payment
用户名超出=Username exceeds
剩余可分配帐号=Remaining unallocated account number
真实姓名不能为空=Real name cannot be empty
分销操作员用户名等检索条件=Distribution operator username and other retrieval conditions
修改失败=Modification failed
分销操作员增加成功=ADD Distribution operator successfully
名称=Name
分销代码不能为空=Distribution code cannot be null
分销常旅客=Distribution frequent flyer
代理=Agent
已分配给下级分销=Assigned to sub distributor
信用卡=Credit Card 
电子邮件地址输入错误=Wrong e-mail address
选择文件=Select File
输入完整的常旅客姓名=Enter the full name of frequent flyer
支付成功=Payment successful
客户存在未结算的订单=Customer has an unfinished order
分销操作员个人信息修改成功=Distribution operator Personal Information modifications succeeded
时间=Time
请输入新的支付密码=Please enter a new payment password
分销客户详细信息=Distribution agent details
公司名称不能为空=Company name cannot be empty
交易成功=Transaction successful
漏单导入客户=Slip Import
用户名不能为空=User name cannot be empty
会计核算记录=Accounting record
用户类型不能为空=User type cannot be empty
账号=Account
上传失败=Upload failed
密码=Password
当前余额=Current balance
操作员变动记录=Operating record
客户延期记录=Customer delay record
分销客户增加成功=Add distribution agent successfully
显示到配送单=Show this on delivery list
重输=Clear
位=Bit
未找到分销客户=No distribution customers found
导入常旅客信息=Import Frequent flyer information
清算失败=failed liquidation
您没有权限进行该操作=You do not have permission to operate
代理可查看=Available for agents
返佣核算记录=Commission count record
确认密码=Confirm Password
请确认新的支付密码=Please confirm the new payment password
终止日期不能为空=End date cannot be empty
表格数据必须为.xls类型=Data must be formed in xls file type.
个人信息=Personal information
单张成人机场建设费=Single Adult airport fee
请重新输入用户数量=Please re-enter the number of users
单张婴儿机场建设费=Single Infant airport fee
增加分销=Increase distribution
关键字=Keywords
单张婴儿燃油费=Single infant fuel fee
请先在【客户结算】内对未结算订单进行结算后再进行操作=Before further operations,settling unfinished orders fisrt.
新密码=New Password
最近登录=Last Login
分销留点=Reserve rate
常旅客组=Frequent Flyer Group
查不到符合条件的数据=No result
银行订单号=Bank Order Number
增加=Add
查询返回=Return
通联支付=Allinpay
未找到分销操作员=No distribution operator found
用户类型不存在=User type does not exist
等待银行清算=Waiting for bank clear
导入失败=Import failed
交易撤销=Transaction canceled
微支付=Micro-payment
单张成人燃油费=Single Adult fuel fee
新密码不能与原密码相同=The new password cannot be the same as the original password
录入人=Operator
持卡人姓名=Cardholder
所选客户无权限修改=The selected customer has no permission to modify
请重新下载或对照EXCEL模板=Please download again or go by the Excel template
邮件地址的输入范例=Example of a mail address entry
上传文件成功=Upload file succeeded
用户类型=User Type
无限额=No limit
信用卡卡号=Credit card number
代码长度超出了=Code length out of limit
请保留一位整数或两位整数或一位小数=Please keep an integer or two-bit integer or a decimal number
名不能为空=Name cannot be empty
更多=More
单张儿童燃油费=Single child fuel fee
额度类型=Credit Type
业务员不存在=Salesman does not exist
请选择文件上传=Please select files to upload
确定转移=Confirm transfer
只能是字母或数字的组合=Can only be a combination of letters or numbers
修改成功=Modification successful
请输入=Please enter
信用额度=Credit limit
分销客户信息修改成功=Modify Distribution agent Information successfully
行=Line
询=xun
重置密码=Reset Password
操作员列表自动换编=Auto-swap for operator list
修改发送短信的手机号会直接修改客户资料中的手机号=Modify the mobile phone number of the SMS will directly modify the mobile phone number in customer data.
对不起=Sorry
用户数量受限=Out of limit
文件=File
你无权访问=You have no authority
分销梯级=Distributor Cascade
不能有空格=No spaces
所属客户=Client
维护操作员=Maintenance operator
验证码=Verification Code
分销名称不能为空=The distribution name cannot be null
乘机日期=Departure Date
位字母数字组合=A combination of letters and numbers
电话号码=Telephone Number
基本信息=Basic information
你无权操作=You have no right to operate
查=Check
包含=Contains
临时额度=Temporary credit
排序=Sort
允许欠款天数不能为空=Allow days of arrears cannot be empty
IP登录记录=Logon Record
英文名=English name
查询城市不能为空=City item cannot be empty
清算成功=successful liquidation 
必须输入IP或帐号进行查询=IP or Account is necessary
城市=Location
格式=Format
提醒=Remind
等待客户认证=Waiting for customer certificating
检索条件=Search by
业务主体不能为空=Business principal cannot be empty
请输入充值额度=Please enter the recharge limit
单张儿童机场建设费=Single children's airport fee
发卡行=Issuing bank
国际卡支付=International card Payment
中文名=Chinese name
修改人=Modified by
不能含三位及惟上重复字母或数字=Cannot contain three or more same digits/characters
操作员名称=Operator name
调账记录=Account record
请检查输入=Please check the input
终止日期错误=End Date Error
请输入您的登录密码=Please enter your login password
返回=Return
导入成功=Import succeeded
当前分销已使用帐号=Current distribution has already used 
您无权访问=You do not have permission to access
支付金额为=Payment amount is
分销客户关系网=Distribution agent relationship network
操作成功=Done successfully
查询结果为空=No result
用户名不能有空格=User name cannot have spaces
最大欠款额度不能为空=Maximum amount of arrears cannot be empty
为佣金=For commission
不能修改授权类型为现金充值=Cannot modify authorization type to cash recharge
返回的数据无效=Invalid data returned
超出授权数量=Out of authorized range
信用方式=Credit Way
不包含=Not included
请输入您的旧密码=Please enter your old password
于=In
其他参数设置变动记录=Other parameter setting change record
QQ号码=QQ
用户数量过多=Too many users
条数据=Data
电子邮箱=E-mail
当前分销总共授权帐号数量=Current distribution total authorized number of accounts
公司LOGO=Company LOGO
单张成人机票价格=Single Adult ticket price
订单信用卡信息=Order Credit card information
当航空公司返点为=When airlines return point is
真实姓名=Real name
您上传的文件类型为=The file type you uploaded is
所属级别不能为空=No empty
生日=Birthday
已使用=distributor used
请输入充值金额=Please input recharge amount
配送商的授信额度设为无限额=Set delivery's credit to No limit
票号数=Amount of Ticket No.
操作员代码=Operator code
自动换编=Automatically editing
账户=Account
系统自动随机生成默认密码为=The system automatically generates a default password randomly as
机票等查询界面默认查询城市=Default city option
取消订单时=When canceling an order
不勾选则强制取消编码=PNR will be canceled if the box is not checked.
勾选上则允许该分销客户通过黑屏预订订单=Check to allow the black screen booking
请选择级别=Please select level
查看级别属性=View Level Properties
开设下级=Open a subordinate
区间的内容=The contents of the interval
操作员代码请至少输入=Please input at least
请稍候再试=Please try again later.
自动将外部PNR转换为自有PNR=Automatically converts external PNR to own PNR
取消编码=Cancel encoding
和多个=how much
个区间包含第=An interval contains the first
首个账户为=First Account
数据检测失败=Data detection failed
允许黑屏预订=Allow black screen booking
填写联系人=Fill in a contact
号码=Number
所属级别=Level of ownership
长度6位的数字或字母组合=6 digits or letters combination
自动生成=Automatically generate
的=de
勾选上则允许该分销客户继续开设所属下级分销客户=Check to allow to generate subordinate 
CT项设置=CT Item setting
个返佣区间头不能大于区间尾=Upper limit should be greater than lower limit
位字母或数字=Bit letters or numbers
勾选上则PNR导入是将自动将外部PNR转换为自有PNR=Check PNR import is to automatically convert external PNR to own PNR
勾选自动生成=Check to generate automatically
允许选择是否取消=Allows the cancellation whether to be made
勾选上则=Check this then
区间不能重叠=Interval cannot overlap
长度=Length
请检查分销编码是否正确=Please check whether the distribution code is correct
允许开设下级=Allow the creation of subordinate
个返佣区间不能为空=cannot be empty
未选择=Not selected
黑屏预订=Black Screen Reservation
勾选上则取消订单时=Check then Cancel Order
业务主体=Business Principal
最大欠款额度=Maximum amount of arrears
注意：密码必须是6位以上、12位以下的数字或字母，且区分大小写。=Attention : Password must contain 6 to 12 characters, digits and letters are necessary, case-sensitive.
帐号=Account
中文姓名=Name(Chinese)
中文姓名不能为空=Chinese name cannot be empty
证件号码不能为空=ID number cannot be empty
请正确输入手机号码=Please enter correct phone number
操作失败=Operation failed
标记为=Mark as
的为必填项=is required
请检查生日输入是否正确=Please check that the birthday input is correct
请检查有效期输入是否正确=Please check that the validity is entered correctly
新增客户=New Customers
使用订座时输入的电话=Use booking telephone number
替换为当前公司的预订电话=Replace with the current company's Booking phone
符合条件的记录有=Fount result
正常使用=Normally use
暂停额度=Suspend limit
可用信用额低于=Available credits below
发送短信到=Send SMS to
清空信用额度=Reset credit 
将停止短信提醒=will stop SMS reminder
授信额度=Credit limit
已用额度=Credit used
增减额度=increase or decrease credit limit
科目=Course
操作员列表=Operator List
所属分销=Upper Distributor
直属上级=Direct Superior
成员=Members
处理=Processing
添加=Add
组名称不能为空=Group name cannot be empty
请选择常旅客=Please select frequent flyer
您确定要删除所选中的常旅客信息=Are you sure you want to delete the selected frequent flyer information
修改会员资料=Modify member Information
取消供应商退废公式=Cancel the Supplier reissue&refund formula
长度已超出=Length exceeded
拼音=Pinyin
请重新做单=Please redo the list.
票手续费=Ticket fees
因私=Private
无法进行下一步操作=Unable to the next step
您的额度仅剩余=Your credit is only remaining
支付银行=Payment Bank
提交纵横天地订单=Submit itour Order
已签约温州银行个人网银专业版的用户=Wenzhou Bank personal net Banking signed user
没有对比结果=No comparison results
如需取消限制=If you need to remove the restrictions
指令导入订单=Import Order by instructions
优惠价=Special Offer
操作写入数据库失败=Writing to database failed
平台出票订单=Platform Ticket Order
请填写英文或拼音=Please fill in English or pinyin
导入已确认订单=Import confirmed orders
银盛渠道支付=yinsheng e-pay
请先取消座位=Please cancel the seat first.
确定增加此婴儿=Confirm adding infant
黑屏处理编码=Modify PNR in Black screen
授权=Authorized
下单=Order
请在自动出票页面选择操作=Please select an action on the Auto ticket page
订单未付款=unpaid order
正在获取航段状态=Acquiring segment status
确定删除选中乘客=Confirm to Delete selected passengers
收款方=Payee
保存订单失败=Failed to save order
抵达城市三字码=Arrival City 3 letters code 
当前订单状态不允许取消订单=Cannot cancel current order under its status.
历史订单无法查看=Cannot view history order
匹配到多个三方协议号=Match to multiple 3rd party protocol
正在同步订单=Synchronizing orders
原单无效或无编码=Invalid original order or PNR
点击退票=Click to Refund
会员代码及手机号码均为=Member code/mobile phone number is
翼钱包代扣=Bestpay Wallet Withholding
现返=Now return
无法调用接口=Unable to get interface
温州银行在线支付=Wenzhou Bank Online Payment
异地退款失败=Offsite Refund Failure
预付款支付=Deposit Pay
请输入凭证号=Please enter a voucher number
你确定要对此订单进行该操作=Are you sure you want to operate this order
中国建设银行=China Construction Bank
已取消订单进行同步操作=Order synchronization cancelled
签注信息=Endorsement information
婴儿数已达成人数=Number of infants reached
招行支付=ICBC pay
出票航司=Ticketing airlines
自动出票=Automatically ticket
没有合适运价=No suitable fare
含代理费的=Agent's Fee included
结算金额=Settlement Amount
电子客票=Electronic ticket
废票重出废票=re-Ticketing cancelled ticket
如需临时欠款=If temporary debt are required
人=People
必须在=Must be
原单单号=Original number
自动注册会员=Automatically registered member
送票地址=Delivery address
部分退废不能同步=Partial refund cannot be synchronized
预订方式=Booking method
日=Day
支付签名初始化失败=Payment Signature Initialization failed
拒绝退票=Refund refused
请选择要分离的乘机人=Please select the passenger to separate
航程信息=Voyage information
航班取消=Flight cancelled.
应退合计=Total refundable amount
退票=Refund
请重新查询预定=Please search and book again
请选择需改期的乘客=Please select the passengers to reschedule.
出票代扣成功=Ticketing withholding successfully
已经被使用=has been used
不积分=no bonus
在线支付=Online payment
保单类型=Type
产生的改期单将自动调到=The resulting rescheduled order will be automatically transferred to
政策对比=Policy comparison
已用航段费用=Used segment fee
警告=Warning
机场柜台办理=Airport Handling
取票日期=Pick-up Date
不能对退废订单进行同步操作=Cannot synchronize the refund&reissue order
原同行价=peer price
费率为每笔=Rates per deal
订单写入数据库失败=Order Write to database failed
航司单号=Airlines List Number
查询订单信息失败=Failed to get order information
联系电话保存到会员信息=Save Contact number to member information
编码导入=Import PNR
支付宝信用代扣=Alipay Credit Withholding
订单写入成功=Modify order successfully
其它乘机人作为常旅客=Set other passengers as frequent flyer
银联在线支付=UnionPay Online Payment
紧急处理=Emergency handling
给您带来不便敬请原谅=Sorry for your inconvenience.
出票失败=Failed
格式不再支持=Format is no longer supported
你的预付款余额=Your prepayment balance
运价错=Wrong fare
商联商用预付卡加密通信错误失败=30pay prepaid card encrypted communication failed
换编码并出票=Change PNR number then ticket.
配送日期=Delivery date
快钱支付=Quick Pay
同步订单数据=Synchronizing Order Data
税=Tax
请正确选择序号=Please select the serial number correctly
支付宝=Alipay
请取消该订单=Please cancel the order
工行在线支付签名初始化失败=ICBC Online Payment signature initialization failed
请输入舱位=Please enter the class
赠送两份=Two free gift.
您的银行卡需开通网上支付功能方可进行支付=Online payment function of your bank card is needed!
不能自动出票=Cannot ticket automatically
如需重调=If you need to retrieve
补录常旅客=Complement Frequent flyer
差价调账单=Post adjustment bill
票盟=Ticket Union
请按实际情况选择退废票的类型=Please select the reissue&refund ticket type.
百拓=Baitour
退保险=Refund Insurance
交通银行网上支付=Bank of communications Online payment
正在处理数据=Processing data
送=Send
请检查保险方式选项=Please check the insurance options
统一=Unified
将乘客人保存到会员常旅客=Save the passenger to a member of the frequent flyer
客户存在逾期未结账单时禁止继续出票=No more ticketing allowed when customer has overdue bill
兴业银行跨行网上支付=Industrial bank inter-bank online pay
新退废订单=New refund&reissue orders
生产公钥=Production Public key
该平台未支持全自动=This platform does not support fully automated
删除婴儿=Delete infant
新订单人数超出原单人数=Number of new orders exceeding original number
退款单=Refund Order
返佣=Commission discount
无法获取票号信息=Unable to get ticket information
老版护照=Old Passport
未找到自动出票员=No auto operator found.
请确认只取消订单=Please confirm that only cancelling order
票面=Coupon
是否赠送=Gift or not
平台单号=Platform number
因超过三次指定的订单号无效=Invalid order number due to three times try
汇付电子支付=ChinaPnR Electronic Payment
头等舱=First Class
扩展指令只支持=Extension Instructions only support
如果因特殊原因=If for special reasons
中国邮政=China Post
证件号码等填写的内容是否正确=Please check the ID info
您的余额=Your balance
出发和抵达航站楼中间用=In the middle of departure terminal and arrival terminal, there is
没有适用的平台政策=No suitable policy
原单号=Original order
已出票订单人数和编码内的人数不一致=Number of ticketed passengers and PNR are not equal.
订单已成功提交到九元航空=Order has been successfully submitted to 9air
需要换编码=Need to change PNR
会员卡号=Membership card Number
您输入的=You entered
给该订单积分=Bonus for this order
只需填写姓名=Name only
错误代码=Error code
政策不一致=Inconsistent policy
最低价=Bottom price
银联=UnionPay
其他出票方式尚未开放=Other ticketing way is not open
在线=Online
必须等于订单=Must be equal to the order
退单结算价=Refund Settlement Price
请在采购设置里设置=Please set this in purchase settings
星期六=Saturday
重复请求=Repeated Request
已提交退票单=Refund list submitted
运价信息提取失败=Fare Info Extraction Failure
机取=Machine Pickup
第一页=First page
支持以下多家银行借记卡和信用卡的支付=Support debit and credit card payments for the following banks
上一页=Previous page
该订单已过作废时间=This order has expired
操作类型无效=Invalid operation type
员工编号=Employee number
中国银行=Bank of China
取票地址=Pick-up Address
不允许废退票=No refund is allowed
此订单为易行天下平台出票订单=This order is ticketed by Yeexing.com .
是否要支付=Whether to pay
指令格式错误=Instruction format Error
请在此上传全退证明=Please upload a full refund here
订座记录产生失败=Booking record failed
解挂客票=Restore Suspended Tickets
中文姓名无法输入的汉字时=When there are Chinese characters cannot be typed
存在改期单=rescheduled order exists
对比过程为=The contrast process is
乘机人姓名不能为空=The passenger name cannot be empty
废票=Cancel
拒绝出票=Refuse to vote
机票作废单=Ticket Cancellation List
出票=Ticketing
网络通信错误=Network communication error
调账=Adjustment
请输入完整的订座记录编号=Please enter the complete PNR
以中国大陆护照上的位置为例=Take the indicated position on Chinese mainland passport as an example
订单航段信息查询为空=Found no segment info in order
订单尚未付款=The order has not been paid yet
操作记录=Action Record
银盛支付加密通信错误=Yinsheng Payment for encrypted communication error
正在查询=Searching
请确认是否按退票处理=Please confirm whether regard this as refund
地址=Address
无=No
航班日期为=Flight date is
隐藏差旅详情=Hide Travel Details
置顶规则不允许=Top rules do not allow
请选择需要删除的乘客=Please select passengers to delete
请认真检查=Please check carefully
平台代码不能为空=Platform code cannot be empty
订单不符合操作条件=Orders do not meet operating conditions
机票改期单=Ticket reschedule sheet
分别生成对应的新编码和新订单=Generate corresponding new codes and new orders separately
分销=Distribution
请通过指令=Please use instruction to
含税底价=Tax Basis
易行天下平台订单=Yeexing.com platform order
订单已超出支付时间=Order exceeded payment time
交行支付初始化失败=Bank of Communication Payment initialization failed
请选择要删除内容=Please select what you want to delete
国际卡获取证书信息失败=International card failed to get certificate information
请选择价格=Please select price
将该订单的乘客名单覆盖到会员名下=Put this order's passengers' list under member's name
请严格按照登机时所用证件上的信息填写=Please fill in the information strictly as boarding one
电商=Commerce
同步失败=Sync failed
快付通无卡支付=Quick Pay No card payment
请等待审批=Please wait for approval
优惠=Special Offer
导入编码时以第二个乘机人作为持卡人=The second person as the cardholder when importing the PNR
自有=Own
会员资料=Member Information
实退加收=Withdraw and collect
深圳发展银行=Shenzhen Development Bank
会员代码=Member Code
银联快捷支付=UnionPay Quick Payment
中信银行=CITIC Bank
无对应数据=No corresponding data
分离编码=Separate PNR
建行支付=CCB Payment
母单净利=Net receipt of parent list
电子邮件=E-mail
隐藏=Hidden
对比中间件请求失败=Failed to compare middleware
我们也会及时通知您=We will inform you in time
的退票信息=Refund Information
招商银行=China Merchants Bank
自动出票失败=Automatic ticket failure
已用税金=Used tax
中国工商银行企业版=ICBC Enterprise Edition
底价=Minimum Price
英文姓名必须使用=English names must be used
信息=Information
信用额度授权=Credit Limit Authorization
不能为空=Cannot be empty
办理方式=Processing method
广发行=CGB
运价编号=Fare number
乘机人出生日期不能为空=The birth date cannot be empty.
返回调度中心=Back to dispatch center
支付金额=Payment Amount
审批挂账=Check credit
此操作用于原纪录编码退废票后重新出票=This operation is used to ticket the refunded or reissued PNR.
请重新查询航班=Please search again.
已换登机牌=Changed boarding pass
同行金额=Peer Amount
无法全部删除=Cannot delete all
退废机构=Reissue&Refund Agency
返回上一页=Return
打印行程单=Print Itinerary
已被操作员=has been operated by operator
的短信已成功加入待发列表=SMS has been successfully added to the outgoing list
无卡支付=No card payment
无法自动出票=Unable to automatically ticket
借记卡信用卡电话支付=Debit or Credit Card phone Payment
去支付=To pay
请输入正确的城市代码=Please enter the correct city code
其它=Others
执行指令报错=Error code
可用拼音=Pinyin is available
内容后面=Behind the content
最后一页=Last page
只退税=Only refund tax
分钟内支付=Payment in
中国银联电子支付=China UnionPay Electronic Payment
因为国际机票变化频繁=Because of frequent changes in international fares
办理时间=Processing time
机票追位单=Ticket tracking List
供应商帐户余额不足=Insufficient vendor account balance
张额度=Credits
星期日=Sunday
拒绝改期=Refuse to reschedule
请慎重=Please be careful.
记录编号不能为空=PNR cannot be empty
改期=Rescheduled
订单已被=Order has been
本网站采用网银在线安全支付平台=This website uses the NET Silver online security payment platform
网上汇款免手续=Internet remittance free of charge
保险变更=Insurance change
翼=Wing
协议号=Protocol number
有=Yes
编码包含多个运价=PNR contains multiple fares
已用票价=Used Fares
应退采购商合计=Total receivable Buyers
命令格式错误=Wrong command format
不要保险=No insurance
修改航段=Modify Segment
原编码=Original PNR
旅行目的=Travel purpose
金额有误=Wrong amount
月=Month
工商银行=ICBC
温州银行=Wenzhou Bank
星期三=Wednesday
与=and
订单积分写入成功=Successfully import order bonus
员工=Employees
请选择与购票方的退废类型=Please select the type of refund with the buyer
正在获取=Getting
婴儿超出=Baby Beyond
已用佣金=Commission used
请正确输入充值金额=Please enter the recharge amount correctly
被自动截断=is automatically truncated
确认更换=Confirm Replacement
中国民生银行=Minsheng Bank of China
成功=Success
自动出票开关尚未开启=Auto-ticket switch is not open
编号为=Number is
存在两个不同的票价=There are two different fares
只能使用=can only use
出票类型为空=Ticketing type is empty
正在获取票号=Getting ticket
请在改期单上操作退票=Please operate the refund on the rescheduled list.
无成人=No adult
银盛支付=Yinsheng Payment
国际卡在线支付签名失败=International card online Payment signing failed
显示=Display
立即解冻该笔资金=Unfreeze the funds immediately
打印=Print
我要出票=I want to ticket.
请检查送票日期输入是否正确=Please check that the delivery date is entered correctly
拼音或英文=Pinyin or English
自动拒绝出票=Automatically reject ticketing
不存在=does not exist
上海农村商业银行=Shanghai Srcb Commercial Bank
改期单号=Rescheduled number
您的银行卡需开通网上支付功能方可进行网上支付=Your bank card must be opened online payment function
订单号无效=Invalid order number
记录内容不能为空=Record content cannot be empty
请使用=Please use
送票时间=Delivery time
必须使用=Must use
谢谢您使用=Thank you for using
上海浦发行=SPDB Bank
非当日出票不能同步=cannot synchronize if the ticketing date is not same as its ordering date
下载附件=Download attachments
中国光大银行=China Everbright Bank
星期四=Thursday
请勿重复操作=Do not repeat
需要确认出票后才可以支付=You need to confirm ticketing before you pay.
华夏银行=Huaxia Bank
锁定=Lock
取消订单的同时=Cancel the order at the same time
的年龄范围=The age range
输入婴儿=Enter Baby
修改信息成功=Modify Information successfully
添加航段=Add segment
无法获取到该编码的价格信息=Unable to get fare info of this PNR
重复改期=Repeated reschedule
经停=Stopover
查看帮助=View Help
机票降舱退票单=Downgrade Refund List
获取退票信息失败=Failed to get refund information
支持中农工建等多家银行在线支付=Support many banks online payment
配送费=Delivery fee
一键补位=One-key cover
联通固网支付=Unicom Network payment
机型=Models
暂无数据=No data
出票机构=Ticketing agencies
乘机人信息错误=Passenger Info Error
您只需使用手机微信的扫一扫功能=You only need to use the sweep function of WeChat
万元以上=More than Million Yuan
奖罚单=Rewards and punishments
不符合平台政策范围=Inconformity to the platform policy
已存在改期单=A rescheduled order already exists
工行企业网上支付=ICBC Enterprise Online Payment
担保挂账=Guarantee Ledger
或者需导入的=or import
重复导单=Repeated import
编码对应的订单已存在于系统中=PNR corresponding order already exists in the system
请输入航班号=Please enter your flight number
重新导入编码=Retry import PNR
请使用中文或英文=Please use Chinese or English
立即重发退款请求=Re-send a refund request now
平台订单=Platform Order
身份证号码=ID number
分钟内=Minutes
以及=and
原单至少保留一个乘机人=At least one passenger in original list.
企业版=Enterprise Edition
支付失败=Payment failed
手续费=Handling fee
航空公司协议号=Airline Agreement No.
航司二字码=Airline 2 letters code
请先选择航班日期=Please select departure date first
兴业银行=Industrial bank
需要授权=Need authorization
确定增加此航段=Make sure to increase this segment
广州市商业银行=Guangzhou Commercial Bank
请您在新打开的页面进行支付=Please pay on the newly opened page
返回重新支付=Return to pay again
百拓平台订单=Baitour Platform
请返回重新核对姓名=Please return to recheck name
小于航空公司的退票费=Less than airline refund fee
其他金额=Other amount
含税=Tax-Included
航空公司实退=Airlines actual refund
购买的电子客票=Purchased E-Ticket
导入新会员时不能输入=You cannot input while importing new member
请稍后重试=Please try again later
请确认是否要分离编码=Please make sure that you want to seperate PNR
机票预订单=Ticket Booking
机票订单微信支付=Ticket Order WeChat Pay
已暂停=Paused
预订客户=Book a customer
升舱换开=Upgrade Reissue.
服务费用=Service fee
星期五=Friday
公务舱=Business class
多级分销订单禁止同步=Prohibited synchronization for Multilevel Distribution orders 
工行在线支付签名失败=ICBC Online payment signing failed
退废票重出=Ticketing refund ticket
发起出票请求=Ticket request
删除成功=Delete successfully
点击给该订单写入积分记录=Click to write an bonus record for the order
支持图片=Support Pictures
订单已取消订单信息查询失败=Order has been canceled,Searching Order information failed
分离婴儿=Separate baby
对比中间件网络错误=Compare Middleware Network errors
配送方式=Delivery mode
联系人手机号码不能为空=Contact phone number cannot be empty
同步编码=Synchronize PNR
选择航班日期=Select Flight Date
自动导入会员并将订单计入会员名下=Automatically import the member and count the order into the member's name
获取原单价格信息失败=Failed to get original price information
只能是数字=Only numbers.
取票时间=Ticket pickup time
提交退票之前=Before submitting refund
本窗口将在=This window will be
导单成功=Successfully
支付完成前请不要关闭该窗口=Please do not close this window until payment is done
北京银行=Beijing Bank
不需要收回行程单=No need to retract itinerary
乘机人证件有效期不能为空=The validity period of the passport holder cannot be null
隐藏航班明细=Hide Flight Details
机票取消单=Canceled ticket
商联商用预付卡=30Pay Prepaid Card
请正确输入婴儿英文名称=Please enter the infant English name correctly
不允许输入返佣信息=Do not allow to enter rebate information
银盛支付加密通信失败=Yinsheng Payment encrypted communication failed
商联商用预付卡加密通信错误=30Pay prepaid card encrypted communication error
其它费用=Other costs
即可通过微信进行支付=Can be paid through micro-letters
非工作时间=Non-working time
交通银行=Bank of Communications
送票时间不能为空=Ticket delivery time cannot be empty
变更手续费率=Change fees rate
如需邮寄请输入邮寄地址=Please enter your mailing address.
账户尚未开通自动出票权限=The account has no automatically ticket authorization
请输入有效的保险份数=Please enter a valid number of copies
星期一=Monday
净价加收=NET addition
小时=Hours
汇付天下电子支付=ChinaPnR electronic payment
汇付余额代扣=ChinaPnR Withholding
的退票费=Refund Fee
退票费=Refund Fee
是否同时取消编码=Whether to cancel PNR at the same time
陪护成人=Accompanying adult
请输入签注内容=Please enter the endorsement content
超出政策误差范围=Out of policy bias range
已用票价的返佣金额=Rebate of fares used
分钟内完成支付=minutes to complete the payment
变更手续费=Change fees
银联支付=UnionPay payment
预订失败=Subscription failure
实收价=Paid-in price
申请退废=Apply for Refund&Reissue
三方协议政策已暂停=Tripartite agreement policy suspended
所有的票价=All fares
结算后返=return after settlement
出票锁定的订单不允许同步编码=The order that the Ticketing is locked does not allow synchronous PNR
匹配不到对应的退票航段=No matching to corresponding refund flight segment
舱位代码=Cabin Code
出票价格=Ticketing price
无法继续出票=Unable to proceed ticketing
补位失败=Complement failed
您的充值请求提交成功=Your recharge request was submitted successfully
请联系系统管理员=Contact your system administrator
订座成功=Booking successfully
小太阳扩展指令=Skyecho Expansion Command
出发城市三字码=Departure City three letters Code
配送方式不能为空=Delivery method cannot be empty
删除航段=Delete segment
到达城市三字码=Arrival City three letters Code
兴业跨行网上支付=Industrial bank inter-bank online pay
编码内容为=PNR content is
飞行时间=Flight time
扣除机票税=Tax on air tickets
会员剩余积分小于原订单所得积分=Member remaining points less than the original order
支付宝支付=Alipay Payment
获取不到航段信息=cannot access to segment information
已预订过该航班=The flight has been booked
航空服务器尚未起动=The air server hasn't started yet.
获取航段状态失败=Failed to get segment status
结果=Results
暂时预留=Temporarily reserved
填写说明=Example
网上支付帮助=Online Payment Help
号航站楼=Terminal
统一已用机场税=unified used Airport Tax
同步订单=Synchronize orders
酒店预定=Hotel Booking
查询不到您指定的订单=Found no result
退废重出单=Reissue&Refund Re-ticket list
不能继续=Cannot continue
降落=Landing
更换编码=Replace PNR
只有部分航空公司开通了=Only some of the airlines are open.
机票人工降舱单=Ticket manually downgrade list.
您预订的航班座位已被=The seat you have booked has been
改期机构=Reschedule agency
杭州银行=HZ Bank
扣预付款数据写入失败=Withholding prepayment Data Write failed
自动订座=Auto Booking
订座记录取消失败=Booking record cancellation failed
母单同行价=Parent order Peer Price
您发往=You send To
退票导入数据保存失败=Refund Import Data Save failed
立即触发退款请求=Trigger a refund request immediately
出票导单失败=Ticketing order import failed
来源=Source
正在为您跳转页面=Skipping page for you
展开所有航班=Expand All Flights
我们将尽快通过电话或=We will be as soon as possible by telephone or
请正确输入婴儿出生日期=Please enter the baby Birth date correctly
如舱位紧张=such as short for cabin
转人工操作=Go to manual operation
请认真检查机场税价格是否正确=Please carefully check the price 
添加乘机人=Add a passenger
机票电子客票=Ticket Electronic ticket
中国农业银行=Agriculture Bank of China
借记卡信用卡无卡支付=Debit/Credit card no-card payment
与您联系=Contact you
代理费率=Agent Rates
请核实=Please verify
订单状态不能同步=Order status cannot be synchronized
已出票成功了=successfully ticketed.
指令=Instructions
编码已导入成订单=PNR imported into order
订单已成功提交到今日天下通=Order has been successfully submitted to jinri.cn
航司名称=Airlines name
报价类型=Fare type
保险数量=Insurance Quantity
编码已取消=PNR canceled
如果有误请及时联系我们更改=If it's wrong please contact us to change
手机号码不能为空=Phone number cannot be empty
未找到=Not found
扣除记奖价=Deduct the prize price
确认支付=Confirm Payment
出现两条以上出票队列=There are more than two ticketing queues
改期中止=Reschedule suspended
定期配送=Regular delivery
提取编码内容失败=Failed to extract PNR content
票号无效=Invalid ticket
女士=Ladies
订座记录信息提取失败=Booking Record information extraction failed
您可以选择=You can choose
保险同行价=Insurance Peer Price
异地取票=Ticket off-site pickup
输入参数有误=Incorrect parameters input
请输入航班日期=Please enter your flight date
无成人不能添加婴儿=Cannot add infant without adult
发票=Invoice
协议挂账=Protocol Ledger
分离编码成功=Separate PNR successfully
错误=Error
网上预订系统=Online booking system
钱包付款=Wallet Payment
商联商用预付卡支付=30Pay Prepaid Card Payment
可在参数设置里取消=Can be canceled in parameter settings
但找不到调账单=But cannot find bill
系统无此会号=System does not have this number
订单同步=Order Sync
政策=Policy
订单无效=Invalid order
的订单了=Orders.
如果您所填写的电话=If you fill the phone
再删除多余运价信息=Remove excess fare information
出票队列状态=Ticketing Queue Status
用户身份校验失败=User authentication failed
以平台最终返回的退废手续费为准=Based on the final refund&reissue return fees of the Platform
确认修改订单信息=Confirm Modify order Information
已用机场税=Airport tax
申请订单=Application order
毛利=Gross profit
您无权对其他客户的订单进行出票=You do not have authority to invoice other customers' order
订座记录编号为=PNR is
剩余额度为=The remaining amount is
没有提取到有效的客人名单=No valid guest extracted
请输入要导入的会员号码=Please enter the member number to import
出票代扣失败=Ticketing withholding failed
今日天下通=Jinri.cn
充值单生成失败=Recharge Order generating failed
的姓名='s name
下一页=Next
返佣类型=Type of rebate
未审核=Not audited
已使用的=Already used
退废重出不可以同步订单=The order can not be synchronized when order is reissuing or refunding.
您的预订申请已经被=Your Booking has been
销售中心不能为空=Sales Center cannot be empty
中国工商银行=ICBC
编码内容有=PNR has
请把下面的=Please put the following
国内机票=Domestic
同行价=Peer Price
确认后将产生同原单完全相同的一张新订单=Confirmation will result in a new order exactly the same as the original one
请确认是否要给该订单写入积分记录=Please confirm whether you want to write an bonus record for the order
扣款成功=Successfully paid
导入已配送订单=Import a delivered order
今日天下通平台订单=Jinri platform orders
联程=Multi-leg
环迅信用卡支付=IPS Credit Card Payment
退改签规定=Reissue&Refund Policy
确认价格=Confirm Price
中国邮政储蓄银行=China Postal Saving Bank
建行=CCB 
团队=Group
购买两份=Buy two copies
请输入正确的航班号=Please enter the correct flight number
订单已成功提交=Order has been successfully submitted
信用卡无卡支付=Credit Card no-card payment
您不是预付款用户=You are not a prepayment user
采购商办理日期=Date of purchase
显示订单详情=Show Order Details
打印发票=Print Invoices
您的票号额=Your ticket amount
你无权对该订单做退废=You have no right to refund the order.
直减=Direct reduction
订座=Booking seats
机票改期调整单=Ticket Reschedule adjustment order
由出票方承担手续费少分润=Less service fee profit for ticketing party 
信用卡支付=Credit card Payment
无法获取到票号=Unable to get ticket number
并作废行程单=and cancel the itinerary
保险底价=Insurance bottom Price
请正确输入汇款金额=Please enter the remittance amount correctly
取消采购商退废公式=Cancel the buyer's refund&reissue formula
选填=Select Fill
有误=Wrong
超出乘机人人数=Number of people is exceeded
无须开通网银=No need to open net bank
返佣不能高于不含税=Rebate can not be higher than tax free price
废票手续费=Cancel fee
部分旅客导入的订单禁止同步=imported orders of some passengers are not able to synchronize
取票=Ticket pickup
出票政策与原选择政策不一致=The policy of Ticketing is inconsistent with the original policy
支付宝无卡支付=Alipay no-card payment
成人携带婴儿=Adult with Infant
不能为负数=Cannot be negative
其他费用明细类型=Other Expense type
平台代扣失败=Platform withholding failed
语音支付支持借记卡和信用卡=Voice payment support debit and credit cards
付款方承担手续费=The payer shall bear the service fee
本地出票支付=Local ticket payment
标记分类=Tag classification
强行导入编码=Force Import PNR
没有=No
请确认是否要同步订单=Please confirm if you want to synchronize orders
票价条件=Fare conditions
如需更新订单信息=Update order Information
岁以下=Under age
渤海银行=Bohai Bank
正在为您提交数据=Submitting data for you
请不要再进行修改=Please don't make any changes.
请输入婴儿中文名称=Please enter the name of infant in Chinese
输入是否正确=Whether the input is correct
不允许进行订单操作=Order operation is not allowed
统一已用票价=Unified used Fares
票证来源=Ticket source
同步订单时手工修改的结算=Manually modified settlements when synchronizing orders
退单同行价=Refund Peer Price
请仔细检查原单票号是否为当天出的票=Please carefully check whether the original bill is ticketed same day
不一致=Inconsistent
套餐价=Package price
请确认是否要自动进行订座=Please confirm whether you want to book automatically
订单已付款=Order has been paid
团号=Group number
返平台=Back to Platform
办理中=Processing
正在为您查询数据=Querying data for you
重复订座=Repeated booking
汇付信用卡无卡支付=ChinaPnR credit card no-card payment
统一已用佣金=Unified used Commission
超出亏损范围=Out of loss range
已支付的订单无法取消=Orders that have been paid cannot be canceled
预付款或信用扣款数据写入失败=Prepayment or credit deduction data write failed
提取失败=Extract failed
不允许重复导入=Repeated import not allowed
关闭窗口=Close window
退票单不允许进行该操作=Refund order does not allow this operation
注册为会员=Register as a member
请确认是否要分离该订单婴儿乘客=Please confirm whether you want to separate baby passengers
订单有三方协议=The order has a tripartite agreement
已转人工操作=Changed to manually operation
中心订单不允许进行=Central order not allowed
自动挂账失败=Automatic Ledger failed
已废=has been canceled
订单状态无效=Invalid order Status
部分航段订座不成功=Partial segment booking is unsuccessful
客户信息=Customer Information
不能继续操作=Cannot proceed operation
已退款=refunded
级别=Level
字母或者组合=Letters or combinations
订座记录已取消=Booking record canceled
无法标记为退票完成=cannot be marked as refund completion
机场代码=Airport code
已收银订单不能同步=The cashiered order cannot be synchronized
早于限定的退票时间=Earlier than the limited refund time
办理完成=Processing completed
客人前台办理=Guest reception
删除旅客=Remove passengers
编码内无婴儿信息=No infant information in PNR
航段信息提取失败=Segment Information extraction failed
退票不再优惠采购商=Refund no longer preferential buyers
内容加到=Add content to
免收跨行支付手续费=Free inter-bank payment fee
出票渠道对比结果选定为=Channel comparison results are
支付密码错误=Wrong Password 
已经存在于订单=already exists in the order
乘客信息=Passenger information
来选择运价=To choose fare
原结算价=Original settlement price
不可高于订单销售价=No higher than order sales price
中间件返回的签名验证无效=Invalid signature validation returned by the middleware
客规=Customer Regulations
申请退票=Application for Refund
不能导入编码=Cannot import PNR
删除乘机人=Delete a passenger
网上支付功能尚未开通=Online payment function is not opened yet.
销售规定都要与客服热线=Sales demand all should go to hotline
提交在线退票单=Submit Online Refund Form
订单已成功提交到票盟=Order has been successfully submitted to the ticket Union
您的浏览器不支持=Your browser does not support
订单内至少保留一个乘机人=Keep at least one passenger in the order
请确认是否要删除=Please confirm you want to delete
必填=Required
预付款充值=Deposit Recharge
已挂起=Suspended
业务=Business
如需再次导入改期单请使用=To import the reschedule order again, please use
确定修改此航段=Confirm changing this segment
分离航段=Seperate segment
初始密码=Initial password
添加配送地址=Add delivery address
删除婴儿写入成功=Delete Infant Write successfully
获取运价失败=Failed to get fares
中间件请求失败=Middleware request failed
订单已成功提交到=Order has been successfully submitted to
采购商=Buyers
不返佣=No commission rebate
应付总计=Total
进行搭桥=To bypass
出票获取政策失败=Failed to get Ticketing policy
只保留一个=Only keep one
点击选择=Click to select
正常导入编码=Normally import PNR
剩余短信=Remaining SMS
资金解冻失败=Failed to unfreeze funds
只有正常订单才可以出票=Only normal orders can be ticketed.
抱歉=Sorry
可以登录网银选择代理业务完成民航机票订单支付=Can log into net bank then select surrogate business to complete air ticket orders payments
异取=Offsite get
保存常旅客=Save Frequent Flyers
已支付成功=Paid successfully
中国银行支付网关签名失败=Bank of China payment gateway signing failed
被=Be
需在订单里提供付款人的手机号码=Need to provide the payer's mobile number in the order
快钱无卡支付=Quick Money without card payment
更换舱位=Change cabin
与出票方面退票原因=Refund reasons
必须等于订单销售价=Must be equal to the order sales price
汇付信用代扣=ChinaPnR Credit Withholding
到百拓=To baitour
赠送金额在充值成功后会自动入账=The bonus will be recorded automatically after the recharge is successfully done.
出票锁定=Ticketing locked
未收回发票=Invoice not recovered
应退总金额=Total Refund Amount
网上支付金额=Online Payment Amount
退款请求待发送中=Refund Request in sending line
位数字=Digits
金额不正确=Incorrect amount
将联系地址=Contact address
联系信息不能为空=Contact information cannot be empty
的母单净利小于退废单的净利=The net profit of parent order is less than reissue&refund order
与自发=and spontaneous
扫描此二维码=Scan the QR code
请稍后再试=Please try again later.
定期=Regular
乘机人序号出错=The passenger number is wrong.
失败=Failed
格式如=Format such as
已支付订单不允许同步=Paid orders are not allowed to sync
结果失败=Failed
订座记录写入系统数据库失败=Failed to write PNR to system database
送票员=Ticket courier
南京银行=Nanjing Bank
新订单=New Order
请备注清楚转入账户信息=Please make clear the account information
不能导入订单=Cannot import order
紧急订单=Urgent order
请删除多余运价信息=Please delete excess fares information
一经选中无法再修改此次签注=No more modification once selected this endorsement 
请重新核对=Please check again.
赠送保险=Free Insurance
您只需拥有任何一张银联标识银行卡=You only need one UnionPay bank card
您确定要取消平台订单吗=Are you sure you want to cancel the platform order
发票号=Invoice number
签名错误=Signature Error
无需开通网银或网上支付功能=No need to open net bank or online payment function
返佣类型为=The type of the rebate is
北京农村商业银行=Beijing Rural Commercial Bank
此退票单有成人和婴儿=This refund list has adult and infant.
隐藏订单详情=Hide Order Details
未找到对应订单=No corresponding orders found
净价=Net
因公=Due to company business
不能确认出票=Cannot confirm the ticket.
中原银行支付=Zhongyuan Bank Payment
且退票单号为空无法重新获取=And the refund number is empty and cannot be retrieved.
而不取消编码=Without canceling the PNR
的会员注册短信已自动加入待发列表=Member Registration SMS has been automatically added to the sending line
无位=No bit
修改证件信息失败=Failed to modify certificate information
采购账号尚未维护=Purchase account is not yet been maintained
充=Charge
修改信息失败=Failed to modify information
免票=Free
平安银行=PingAn Bank
请选择要删除的航段=Please select the segment to be deleted
此=This
送票地址不能为空=The delivery address cannot be empty
订单重复录入=Repeated Order Entry
申请=Application
从=From
送票上门=Hone delivery
请检查编码状态=Please check the PNR status
即可快捷支付=Can be quickly paid
提交易行订单=Submit Yeexing Order
的票款=The ticket
不可高于订单=No higher than order
汇款金额=Remittance Amount
上海浦东发展银行=Shanghai Pudong Development Bank
入库之后的=After storage
当前订座记录内容=Current PNR content
产生的退废单将自动调到=Refund result will be set as
邮寄地址=Mailing Address
是否取消编码=Whether to cancel PNR
因航空公司或机场原因要求全退的=Full refund due to airline or airport demand
号分隔姓和名=Number separate last name and name
同步=Synchronization
无效=Invalid
确定删除此航段=Confirm deleting this segment
取消=Cancel
我们将尽快与您联系=We will contact you as soon as possible
广东发展银行=Guangdong Development Bank
输入编码敲回车即可提取编码的航班信息=Input PNR then push Enter button for flight info.
没有任何可对比的出票渠道=There's no ticketing way to compare
产品类型=Type
确认改期=Confirm Reschedule
乘机人证件号码不能为空=The flight ID number cannot be empty.
退废票不能同步=Reissue&Refund ticket cannot be synchronized
系统警告=System warning
深发行=Shenzhen Development Bank
结算合计=Settlement total
运价基础=Fare basis
付款方式=Payment method
会员注册成功=Member Registration successful
编码已取消不能同步=Canceled PNR cannot be synchronized
招行=China Merchants Bank
您目前没有权限黑屏预订订单=You do not have permission to order in black screen mode currently.
供应商=Suppliers
请选择支付方式=Please select payment method
订单已成功提交到易行天下=Order has been successfully submitted to Yeexing
接收的数据为空=The received data is empty
机场取票=Airport pickup ticket
段=Segment
订单价格=Order price
保存配送地址=Save delivery address
开通网上支付功能帮助请点击=Open Online Payment function help please click
机票调账单=Ticket transfer Bill
已出票的订单无法取消=Orders that have been ticketed cannot be canceled
每张票亏损金额为=Each ticket loss amount is
工行个人支付=ICBC Individual payment
自动注册会员成功=Membership auto-registration successful
请咨询您银行卡的发卡行=Please consult your bank card issuer
汇付信用卡支付=Pay by ChinaPnR credit card
退废票文件=Reissue&Refund file
默认支付方式尚未设置=Default payment Method not set
提交航信订单=Submit an TravelSky order
国际=International
取票机场=Ticket pickup airport
禁止同步=Prohibit synchronization
请确认是否要删除该订单婴儿乘客=Please confirm if you want to delete infant passengers
查询订单状态=Inspect order Status
含税实收=Tax net charged
分钟内未完成支付=Payment is not completed within minutes
宁波银行=Bank of Ningbo
订单内至少保留一个航段=Keep at least one segment in the order
分=Minute
您预订的航班座位没有位置=No seat available
付=Pay
航站只能输入=Terminals can only enter
保险销售价=Insurance Sales Price
机票退票单=Ticket Refund List
贵公司今天=Your company today
单价=Price
不能对已出票订单进行同步操作=Cannot synchronize the ticketed orders
该=should
确认删除=Confirm deleting
改期成功=Rescheduled successfully
兴业银行支付=Industrial Bank Payment
如有疑问=If there is any question
抵达航站楼=Arrival at the terminal.
降舱退票=Downgrade&Refund
请确认是否要更换编码及舱位并重新订座吗=Are you sure you want to change the PNR and cabin and rearrange the seats
退废操作=Refund operation
联系人姓名不能为空=Contact name cannot be empty
请确认是否要分离航段=Please confirm if you want to separate the flight segment.
请检查编码=Please check the PNR.
请输入要发送的短信内容=Please enter the message text
您注册会员失败=Your registration failed
共=Total
请输入汇款金额=Please enter the remittance amount
支付宝余额代扣=Alipay Balance Withholding
国际卡支付签名初始化失败=International card Payment Signature initialization failed
网络超时=Network timeout
出票中不能同步=Cannot sync in the Ticketing process
实收=Paid-in
请输入要发送的手机号码=Please enter the phone number you want to send
导单失败=Import failed
已收款=Received amount
您输入的乘客序号=The serial number of the passenger you entered
待办理=To be processed
无需登记或注册使用账户=No need to register an account
支付手续费=Payment Fees
申请改期=Apply for Rescheduling
出发航站楼=Departure Terminals
您确定要发起代扣请求吗=Are you sure you want to initiate a withholding request
安排上门办理=Arrange the door-to-door processing
变更规定=Change Policy
直接输金额=Direct input Amount
中文=Chinese
未知=Unknown
您将使用额度支付=You will use the credit to pay
号分割=Number Division
统一其他=Unify others
易行天下=Yeexing.com
常旅客写入成功=Frequent Flyer writing Successfully
出票后不能同步=No sync after Ticketinged
确定申请改期=Make sure the application is rescheduled
该订单是当日出票=The order is made and ticketed on the same day
已经入库=Already in storage
舱价=Cabin Price
请选择=Please select
和=and
此订单为今日天下通平台出票订单=This order is ticketed by jinri.cn
重新设置=Reset
行程单=Itinerary
需承担=Need to bear
系统已经存在此编码=This PNR is already existed in the system
不允许进行该操作=Do not allow this operation
页面跳转中=Going to page
内部单号=Internal order number
退废=Reissue&Refund 
此订单将被自动取消=This order will be canceled automatically
以上为单人价格=Above is single price
快钱=99Bill
不能取消订单=Cannot cancel Order
中国银联在线=China UnionPay Online
农行=Agriculture Bank of China
在线充值预付款=Online charge Prepayment
展开=Expand
查看订单内容=View Order Contents
送达时间=Express arrival time
订座失败=Booking failed
选择成本中心=Select cost center
字符=Characters
请联系我们=Please contact us
我们在线支付的时间为=Our online payment time is
乘机人出生日期格式有误=Wrong birth date format
取消平台申请=Cancel Platform Request
修改航段或婴儿=Modify segment or infant
送票日期不能为空=Ticket delivery date cannot be empty
功能=function
中行=Bank of China
票号信息保存失败=Failed to save the ticket number
请确认是否要将乘客人保存到会员常旅客=Please confirm whether to save the passenger to the member frequent flyer.
东亚银行=Bank of East Asia
掉的位置重新=position again
财付通代扣=Tenpay Withholding
其它支付=Other payments
使用支付宝付款=Payment using Alipay
回缴利润=Return profits
退废票自动关联=Reissue&Refund Tickets Automated Association
统一已用燃油税=Unified fuel fee
无法全部分离=Cannot be separated completely
部门=Department
表示导入第一个运价=To import the first fare
如要强行导入=To force import
退票手续费=Refund Fee
确认为准=confirm as standard
航班信息错误=Flight Information Error
加载中=Loading
返佣数据将被系统重新核算=Rebate data will be calculated again by system
统一手续费=Unified service fee
订单签注=Order Endorsement
剩余额度=Remaining credit
国际国内=International and Domestic
退票完成=Refund Complete
订单已取消=Order has been canceled
额度支付=Pay by credit
后台服务程序出错=Background Service error
请确认退票费是否正确=Please confirm the refund fee is correct
供应商应退=Supplier should refund
银联手机支付=UnionPay Mobile Payment
按航空公司变更规定=Change by airline rules
输入的会员代码=Entered Member Code
原始订单=Original order
销售总计=Total Sales
请选择要删除的内容=Please select what you want to delete
查看订单=View Order Details
无法进行支付=Unable to pay
此退票单有成人和儿童=This refund list has adult and child.
客户级别不允许进行=Authority is not enough
您确定要发起付款请求吗=Are you sure you want to initiate a payment request
页面正在加载中=Page is loading
不足本次出票=Not enough for this ticketing.
成本中心=Cost center
航空服务器忙=Aviation Server Busy
与客人退票原因=Refund reasons
航空服务器繁忙=Aviation Server Busy
分离航段成功=Flight Segment Separation Successful
改期单不能同步=Rescheduled order cannot be synchronized
不需=Don't need
经济舱=Economy class
发送邮件=Send mail
未知失败原因=Unknown failure Reason
请注意=Please note
中银=Bank of China
请复查其它费用是否正确后再继续下一步操作=Please review the other charges before proceeding to the next step
不足以支付本次票款=Not enough to pay the fare
订单号不能为空=Order number cannot be empty
导入已出票订单=Import Ticketed Orders
同行合计=Total peers
出票页面正在加载中=Ticketing page is loading
不能对已收银=Cannot be cash
作废=void
接口现金池在线充值=Interface Cash Pool online recharge
无记录=No record
已达上限=reached the upper limit
错误信息=Error message
下单方式=Order method
订单=Order
统一航空公司手续费=Unified airline Fees
后返=Back
已用燃油税=used fuel tax
邮寄=Mail
的三方协议出票只剩余=The tripartite agreement remaining tickets
追位充值=Chaser Recharge
全民付=Chinaums pay
不可变更=Cannot be changed
自动退款失败=Automatically refund failed
李=Li
此订单为百拓平台出票订单=This order is baitour order
网页=Web page
交行=Bank of communications
提交百拓订单=Submit the baitour order
你无权对该订单做改期=You have insufficient authority to reschedule the order.
需等待工作人员审核通过后才生效=Waiting for verification
订单失效=Order Expired
工行=ICBC
利=Profit
记奖价=Price with prize
中转=Transit
订单总价=Order price
是否提交=Yes
例=Case
最大=Maximum size
由于您在下单=Because you are ordering
税金=Tax
原编码订单不做任何修改=No changes to the original PNR order
查看原单=View original order
预订系统保存=Booking System Save
价格信息=Fare Information
特价=Special
点击确认后将根据不同的航司航段=Click on the confirmation will be based on the different airlines segment
小太阳追位充值=Skyecho Chaser Recharge
提交票盟订单=Submit the Order of the Union
请使用指令=Please use the instructions
星期二=Tuesday
平台退废成功后自动扣取退废手续费=After successfully refund on platform, service fee will be charged automatically.
微信支付=WeChat Pay
您预订的机票记录已被取消=Your Booking record has been canceled.
匹配三方协议=Matching Tripartite agreement
签名无效=Invalid signature
支付签名失败=Payment Signature Failed
需技术人员查日志=Need IT support to check the log
请输入订座记录内容=Please enter the Booking record
请仔细阅读并确认您已经同意了订票及退改签规定=Please read carefully and confirm that you have agreed booking and refund rules
请参考指令=Please refer to the instructions
退单净利=Refund order net profit
此退票单有儿童和婴儿=This refund order has child and infant
未定义=Undefined
补位成功=The complement is successful
送票=Ticket delivery
无法导入=Cannot import
该编码获取运价失败=This PNR failed to get fare
称谓=Appellation
商户信息查询失败=Searching Merchant Information failed
提交今日订单=Submit today's Order
退票单已标记退票完成状态=Refund order has been marked refund completed status
出票已代扣成功=The Ticketing has been withholded successfully
农业银行支付=ABC Payment
请选择要删除的乘机人=Please select the passenger to delete
请选择与供应商的退废类型=Please select supplier reissue&refund type
可使用=can use
请输入出发城市三字码=Please enter the departure city three letters code
此订单已做过调账=This order has been adjusted.
请输入到达城市三字码=Please enter the arrival city three letters code
常旅客卡=Frequent Flyer card
自取=Self pickup
查询日期段的天数不能大于=The searching date range can not be bigger than
送票日期=Delivery date
打印订单=Print order
收到=Received
显示差旅详情=Show Travel Details
快速预订=Fast Booking
秒后自动关闭=seconds then auto-close
请确认是否重新=Please confirm whether again
机票将舱作废单=Ticket downgrade cancel list
添加婴儿=Add infant
母单结算价=Parent order Settlement price
调用航信接口错误=Call TravelSky interface error
使用预付款支付=Pay with prepayment
二维码加载失败=QR code loading failed
会员号=Member number
帐号被暂停=Account is suspended
机票做废单=Ticket cancel list
民生银行=Minsheng Bank
供应商办理日期=Supplier Processing Date
注册失败=Registration failed
翼订单=Wing Orders
已锁定出票的订单无法取消=Cannot cancel locked ticketing orders
输入的会员号无效=Invalid membership number
订单信息查询失败=Order Information Checking failed
浙商银行=Zhejiang Merchant Bank
请联系管理员=Please contact the Administrator
按结算价最低出票规则=As bottom settlement price ticketing rules
无需输入=No need to input
年=Year
由于多级分润问题=Due to multilevel profit sharing problem
乘机人证件有效期格式有误=The valid format of the passport is incorrect.
限支付方式=Limited Payment method
订单已成功提交到纵横天地=Order has been successfully submitted to itour
价格=Price
支付密码=Payment Password
选择您要上传的=Select to upload
请检查订票开始日期输入是否正确=Please check whether the booking start date is correct
验证登陆密码=Verify Login Password
行程单申请=Itinerary application
查看非自有票行程单明细=View itinerary details of tickets from other agency
通过=Pass
请确认是否解冻选中票段=Please confirm whether to make the selected ticket section unfrozen
输入备注=Enter notes
旅客姓名=Passenger name
请输入您的支付密码=Please enter your payment password
修改数据失败=Failed to modify data
发送=Send
请确认您的支付密码=Please enter again
可欠款额度=Credit
查看=View
流量=Flow 
样式三=Style Three
写入数据库失败=Failed to write to database
请检查是否有权限进行回收票号=Please check if you have permission to recycle the ticket
代码=Code
可调节边距字号=Adjustable margin&font size
发票管理=Invoice Management
查看编辑分销客户信息=view and edit Agent information
样式八=Style Eight
非=Non-
已设置=is set
退改签手续费=Reissue&Refund fee
充值审核=Recharge Audit
申请查询=Apply for inquiry
领用部门=Receive Department
选择模板=Choose template
请检查终止日期输入是否正确=Please check that the expiration date is entered correctly
发送成功=Successfully sent
利息奖励=Interest Rewards
起始单号=Starting number
小计=Subtotal
YeePay在线支付=YeePay Online Payment
确定设置=Confirm
文件格式错误=File format error
审批失败=failed
帮助=Help
行程单类型=Itinerary type
销售政策=Sales Policy
符合条件的客户有=Fount 
行程单做废后将无法恢复=No restore after canceling itinerary
此申请已审核=This application has been approved
Excel文件第一行为标题=First line is title(Excel file)
外购票号=Other ticket No.
机票状态=Ticket Status
非自有票=Non-own tickets
您输入的支付密码长度必须在6-8位之间=The length of the payment password you entered must be between 6-8 bits
中断交易的分销商=Distributors discard trading
新增交易的分销商=Distributors of New Deals
弹屏通知=Pop-up notices
电子客票行程单=E-Ticket Itinerary
您输入的登陆密码长度必须在6-12位之间=The login password you have entered must be between 6-12 bits
下载Excel文件失败=Failed to download Excel file
确定创建=Confirm
票数=Number of votes
退废单退票办理单=Refund Bill
请检查出票开始日期=Please check the ticket start date
审批=Approval
分配=Distribution
参数错误=Parameter error
请输入要做废的行程单号=Please enter the itinerary No. to cancel
请选择要操作的代打单=Please select the surrogate ticket to be operated
确认操作=Confirm Operation
结束日期=End Date
请检查票号是否输入正确=Please check if the ticket No. is entered correctly
登陆密码不正确=Incorrect login password
录入=Entry
审批通过=Approved
您于=You are
价=Price
按付款方式汇总=Summary by Payment method
请选择客户=Please select customer
已发送=Sent
未用=Unused
弹屏发送状态=Pop-up sending status
已核对=Checked
审核状态=Audit status
总剩余预付款额度=Total remaining prepayments
已欠款额度=Used
样式六=Style Six
核对完毕=done checking
客户机票欠款单=Customer debt list
已取消代打票号=Canceled
请上传=Please upload
终止日期前后顺序是否正确=Whether the end date is in the correct order
审批数量=Approval quantity
代打票号=Substitude No.
请下载=Please download
工行b2b支付签名失败=ICBC's business-to-business payment signature failure
1万元以上=More than 10,000 yuan
退票报表=Refund Report
请输入要做废的行程单=Please enter the itinerary to cancel
航空=Aviation
请检查出票终止日期输入是否正确=Please check that the ticket expiration date is entered correctly
请输入起始票号和终止票号=Please enter the starting ticket and ending ticket
请勿重复进行做废操作=Do not repeat the cancel
冻结=Freeze
出票商返点=Ticket dealer Return point
但保存记录失败=Save Record failed
写入失败=Write failed
已使用或已做废=Used or Canceled
解冻=Restore
立即设置=Set up now
请检查数据是否完整=Please check that the data is complete
中原银行签名错误=ZhongYuan Bank Signature Error
下载数据=Download data
已付款=Paid
以下是中航信返回的出错提示=The following are the error infos returned by travelsky
请输入有效的票号范围=Please enter a valid ticket range
票号 票号=Ticket number
资金将直接打入客户账户=Funds will be directly transfer to customer accounts
汇总表=Summary table
审批人=Approver
数据写入成功=Data Write successfully
打印人=Printer operator
文件不能为空=File cannot be empty
收银报表=Cashier Report
费率为每笔1元/3元/5元=Rates for each 1/3/5 yuan
样式二=Style Two
行程单作废失败=Itinerary cancel failed
请选择要审核的代打票号=Please select the surrogate ticket to be audited
输入负值将从账户扣款=Enter negative value makes account deduction
申请充值人=Applicant
工行b2b支付签名初始化失败=ICBC's business-to-business payment signature initialization failure
票证=Ticket
使用人=User
回收日期=Recycle date
客户级别=Customer level
审批成功=Approved
请在=Please in
自购=Self-purchase
一次性不能输入超过2000张票证=Cannot enter more than 2000 tickets at one time
上传票号=Upload Ticket No.
批准数量=Approved quantity
请点击浏览按钮=Click on the Browse button
您输入的数据的列数不对=The data you entered is not in the correct number of columns
做废=Cancel
登陆密码格式不正确=Incorrect login password format
漏单=Slip
您可以选择是否通知分销客户=You can choose whether to notify distribution customers
请确认是否做废行程单=Please make sure to make the waste itinerary
票价错=Wrong fare
的信息=of information
导入销号=Import sales code
编码未出票=PNR has not been ticketed
邮递费=Mailing fee
获取订单备注信息=Get Order Memo Information
请要申请的数量=	application amount
请输入订单号或PNR进行查询=Please enter the order number or PNR to inquire
开始日期=Start date
新代打票号=New
请检查航班开始日期输入是否正确=Please check that the flight start date is entered correctly
使用日期=Date
审批时间=Approval time
欠款额度设置=debt credit management
负数=Negative
仅适用于国际=Only for International
样式四=Style Four
申请客户=Apply for Customer
特别提示选项=Special Tips
票号来源=Ticket source
设置支付密码=Set up payment password
机票金额=Ticket Amount
查询BSP差错数据=Check BSP error
票号代打列表已存在=Print list is existing
否=No
舱位折扣=Cabin Discounts
已冻结=frozen
请选择要完成代打的代打票号=Please select the ticket No. to be ticketed
已拒绝代打票号=Rejected
按日期汇总=Summarize by date
费用=Cost
正数=Positive
正在转向发送通知页面=Moving to "send notification" page
数据写入完成=Data Write completely
不正确=Incorrect
已有票号=Already have the ticket No.
上传格式=Upload format
请选择操作类型=Please select an operation type
已审核代打票号=Approved 
请输入欠款额度=Please enter the credit
打票机设置=Ticket Printer setting
回收记录=Recycle Records
申请数量=Number of applications
客户代码不存在=Customer code does not exist
您没有权限删除票证=You do not have permission to delete tickets
同行=Peer
内维护=maintenance
只有在小太阳里面进行票证管理并且已使用的行程单号才能做废=Can only cancel used itinerary in Skyecho system
请选择要拒绝的代打票号=Please select the surrogate ticket to be rejected
完成代打=Finish substituted printing
行程单号=Itinerary No.
请输入转帐金额=Please enter the transfer amount
中银E付=BOC ePay
请检查订票终止日期输入是否正确=Please check whether the booking end date is correct.
拒绝=Rejection
请检查=Please check
金额类型=Amount Type
模板=Template
审核=Audit
境外国际卡支付=Overseas international card Payment
使用时间=Use time
乘机时间=Departure Time
发送电子行程单=Send e-Itinerary
不能进行做废操作=Cannot be canceled
终止号段=End segment
收益统计=Income
请确认是否删除=Make sure whether to delete
佣金=Commission
PATA运价信息提取失败=PATA fare information extraction failed
条记录=Record
请检查开始日期输入是否正确=Please check that the start date is entered correctly
分销收益报表=Distribution Profit Report
出票商佣金=Ticket dealer Commission
写入成功=Write successfully
您必须输入您的登陆密码=You must enter your login password
提取编码=Extract PNR
打票机=Ticket Printer
支付状态=Payment status
如需查询每日票证使用明细=Check Daily ticket usage details
审核通过并收款=Approved and charge
没有找到行程单号=Found no itinerary
销号=Delete number
资金管理=Fund
不可取消=No cancel
请检查航班开始日期=Please check the flight start date
已做废=Canceled
税金错=Tax is wrong
已经做废=Canceled
起始日期必须早于终止日期=Start date must be before end date
行程确认单=Itinerary Confirmation list
您无权进行数据操作=You do not have permission to perform data operations
第二步=Second
票证状态=Ticket status
汇总模式=Summary mode
重复票证=Repeated ticket
终止票号=End ticket No.
未设置发件箱=Outbox not set
查询详情=Details
资金存入=Funds deposite
请确认是否冻结选中票段=Please confirm whether to make the selected ticket section frozen
您申请的账户已于=The account you have applied is
此行程单尚未使用=This itinerary has not been used
做废行程单=Cancel itinerary
文档已生成=Document generated
未找到符合条件的结果=Found no result
合计价格=Total Price
禁止继续=No more operation
代理人=Agent
行程单管理=Itinerary Management
未设置=Not set
含所有下级=Include all subordinates
打印退改签规定=Print Reissue&Refund rules
格式的文件=Format files
感谢您的使用=Thanks for using
第一步=First
请正确输入终止日期=Please enter correct ending date
请选择票证所属代理=Please select a ticket-owning agent
新密码格式不正确=Incorrect new password format
未使用=Not used
打印日期=Print Date
8位以下的数字或字母=Digits or letters below 8 characters
已完成代打票号=Completed ticket No. printing by outside
自动充值单写入失败=Automatically Recharge Order Write failed
收款凭证号=Voucher number
初始送流量=Initial delivery Flow
充值结果通知=Recharge result Notification
已成功回收票号从=The ticket has been successfully recycled from
明细表=Details table
信息或票号信息=Information or ticket information
按客户汇总=Summary by Customer
输入的票号段不存在=The ticket section entered does not exist
放弃设置=Cancel
起始号段=Starting number section
充值成功=Recharge successfully
审批拒绝=rejected
改期报表=Reschedule report
的申请被拒绝=Application denied
结算=Settlement
回收人=Recycled by
删除数据会删除票号使用信息=Deleting data will clear the ticket usage information
出票报表=Ticket Report
往前一天=previous day
交易量下降的分销商=Volume descending distributor
请先进行=Please first
请检查出票开始日期输入是否正确=Please check whether the ticket start date is entered correctly
充值人员=Payment operator
行程单做废成功=Itinerary cancel successful
打票机号=Ticket Printer number
张数=Number of sheets
暂时没有相关记录=No record
请选择要取消的代打票号=Please select the ticket to be canceled
请输入终止票号=Please enter the ending ticket No.
请选择使用日期条件查询=Please select to query by using date
支付密码格式不正确=Incorrect payment password format
充值时间=Recharge Time
上传申请=Upload Application
审核成功=Success
您必须输入您的支付密码=You must enter your payment password
起始票号=Starting ticket No.
短信发送状态=SMS Sending Status
打印时间=Print Time
出票设置=Ticket setting
不显示金额=Do not display amount
审核状态为=Audit status is
请选择票证类型=Please select a ticket type
打印行程确认单=Print Itinerary Check form
请重新提交或使用其他方式进行充值=Please resubmit or use other means to recharge
按充值人汇总=Summary by Recharge
请检查你输入的支付密码是否正确=Please check that the payment password you entered is correct
请检查订票开始日期=Please check the booking start date
维护提示信息=Maintenance information
充值人=Payer
进行做废操作=Cancel now
分销客户=Sub-Distributor
回收=Recycle
请要批准的数量=approval amount
日期条件=Date option
申请人=Applicant
如票证录入时无法选择Office号和打票机号信息=If ticket input cannot select office number and ticket printer information
邮件发送状态=Mail status
样式一=Style One
操作后再做废行程单=Cancel itinerary after operation
样式五=Style Five
请正确输入起始日期=Please enter the correct starting date
差错=Error
废票报表=Void Report
请登录使用=Please login
票号管理=Ticket Management
不修改=No modification
打印样式=Print style
打印公司标志=Printer company logo
出发港=Departure city
维护行程单=Maintenance itinerary
邮寄费=Mailing fee
样式七=Style Seven
机票后台=Ticket Backstage
充值完成=Recharge Complete
请输入确认密码=Please enter the confirmation password
新申请=New application
全部客户=All Customers
查看明细=View Details
未付款=Not paid yet
张行程单=Itinerary sheet
请要行程单单价=Itinerary unit price for requirment
公司=Company
请重新输入=Please re-enter
请确认是否做废票号=Please confirm whether to cancel ticket No.
是=Is
订座编码=Booking code
票号段输入重复=Repeated ticket segment
使用=Use
领票部门=Pickup Department
到达港=Arrival Port
抱歉的通知您=Sorry to inform you
客户状态=Customer Status
回收号段=Recycle number Section
银联DNA语音支付支持借记卡和信用卡=UnionPay DNA Voice payment support debit card and credit card
往后一天=next day
终止单号=End number
请输入起始票号=Please enter the starting ticket
出票预定单数=Ticket booking singular
请选择充值员=Please select the Recharge person
客户充值=Customer Recharge
请输入登陆密码=Please enter the login password
领单部门=Receive Department
请输入邮寄地址=Please enter your mailing address
时间段=Time period
实际付款=Actual payment
请检查航班终止日期输入是否正确=Please check that the flight expiration date is entered correctly
发送通知=Send Notifications
选择支付方式=Select Payment Method
预定员=Reserved by
按录入日期查询时显示分配的票证汇总信息=Display the assigned ticket rollup information when the entry date query
不能对已使用的票号=Not to used ticket No
修改信息=Modified details
原有票号=Original ticket No.
与PATA价格=with PATA Price
审批结果=Approval results
请检查您输入的新密码和确认密码是否一致=Please check that the new and confirmed passwords you entered are consistent.
您预订的航班座位已被NO=The seat you have booked has been rejected
请选择预订员=Choose Booking Person
请检查开始日期=Please check the start date
机场大巴时刻表=Airport Bus Timetable
返佣金额=Rebate Amount
上传完毕=Upload Complete
共有三列=Total three columns
单张价格=Single ticket Price
票号代打=Print by ticket No.
成功充值=Successfully recharge
上传=Upload
请正确输入欠款额度=Please enter the credit
我要采购=Purchase
航班预订=Booking flight
政策查看=Policies
交易管理=Transaction management
退废票管理=Refund Management
行 程 单=Itinerary
单证管理=Document management
行程单打印=Itinerary print
发票代打=Invoice
统计报表=Statistical reports
销售日报=Sales Daily
系统设置=Settings
分销管理=Distributor
资金帐户=Funds account
在线充值=Recharge
帐户信息=Account information
基础设置=Basic settings
流量控制=Flow control
修改口令=Modify password
员工管理=Staff Management
常旅客管理=FFP
剩余预付款=Remaining prepayment
常用工具=Tools
安全退出=Secure exit
三字码查询=Search three letters code
基础运价=Base Fare
剩余欠款额度=Remaining credit
剩余流量=Remaining flow
分销系统=Distribution System
次=Time
结算价（返点）=Settlement Price（Rebate）
被暂停=is(are) suspended.
备注：共找到符合条件的订单数有=Note：Found
份/航段=Insurance/Segment
折扣/舱位=Discount/Cabin
注意：正常改期费是保存到税金字段，加收的改期费和升舱费保存到票价字段，这样才能和TSL报表对应=Note:Default Reschedule Fee is included in Tax Column，additional Reschedule Fee and Upgrade Fee are included in Price Column，this way the Fee fits the TSL.
编码内不能存在不同的乘客类型。=Only single type of passenger allowed in PNR.
联系人信息（请准确填写联系人信息）=Contact Info（Attention！Wrong info affect boarding）
注意：密码必须是8位以上3位以下的数字或字母，且区分大小写。请保持支付密码与登录密码不同。定期更换您的密码可以让您的账户更加安全。=Attention：Password MUST be 3 to 8 numbers and letters，CASE sensitive. The Payment Password need differ from Login Password. Change your password periodically makes your account more safe.
第1位乘机人=First Passenger
手机号码；送票服务=Telephone；Ticket delivery
发送短信按钮=SMS
获取PNR内容=get PNR
复制PNR内容获取=Copy PNR
给下级分销=to sub-distributor
已审核，待支付=Checked，Unpaid
抵达城市，查询按钮=To，Search
系统自动获取PNR内容=System gets PNR automatically
友情提示：机票须按航班起飞时间顺序使用，否则无法登机；团队签证无法单独购买机票，详情请咨询签证办理方。=Note：Ticket should be used following the flight departure time order, otherwise boarding is NOT permitted.Group visa can NOT be used separately for individuals buying ticket, learn more from visa issue organization.
真是姓名=Authentic Name
备注：现有客户=Note：Total Client(s)
改期手工录入—选择航段=Manually Reschedule—Choose Segment
注意 ：密码必须是6位以上12位以下的数字或字母，且区分大小写。=Attention ：Password MUST be 6 to 12 numbers and letters，CASE sensitive.
已分配=assign
请输入有效的PNR（小编码）进行导入=please enter valid PNR(Short Code)
起降时间/机场=Time/Airport
SHOPPING实时数据=SHOPPING Status
选择银行（个人版）=Choose Bank (Personal)
如果您的编码不是我们平台系统订座的，请在编码里输入指令授权我们提取编码内容：RMK TJ AUTH=Insert RMK TJ AUTH into PNR if the PNR is NOT booked from our platform；
PNR编码=PNR Code
同步新PNR=New PNR
机建/燃油=Airport Fee/Fuel Fee
提示：没有符合条件的记录，请输入条件查询。=Note：No result，please search again
证件号码；常旅客信息=ID No.；Frequent Flyer
终止/暂停日期=End/Suspended Date
儿童（2-12周岁）=Child(2 to 12 years old)
备注信息：共找到符合条件的订单数有=Note：Found
同步旧PNR=Old PNR
乘机人信息（请准确填写登记人信息，以免影响正常登机）=Passenger Info（Attention！WRONG info affect boarding！）
关闭按钮=Close
已支付，待出票=Paid，Preparing
期限；联系信息=Indemnity limit；Contact
Total=Total
前台自取；“我已阅读并同意《网络电子客票协议》”，同意以上条款=Front desk Pickup；“I agree 《Network Electronic Ticketing Agreement》”Agree
上传延误/病退证明=Upload Delayed/Retire Certificate
PNR编号=PNR Number
含证件号码的乘机人姓名=Name of passenger with ID number
会员注册=Member Registration
请谨慎使用，特价票价格可能会有误=Caution! The price of special tickets may be incorrect
机票总价格=Total ticket price
按录入日期查询时显示分配的票证汇总信息，如需查询每日票证使用明细，请选择使用日期条件查询。=Entry Date (rollup) shows assigned tickets info.Use Date (detail) shows ticket using details by each day.
删除模版=Delete template
短信记录=SMS Record
登记提醒=Boarding Reminders
申请出GP票=Apply for GP tickets
请确保PNR内容真实准确，虚假PNR出票方有权拒绝出票。=Please ensure that the PNR content is true and accurate, with false PNR the drawer has the right to reject the ticket.
请确认每个旅客均已输入证件号码SSR FOID=Please confirm that each passenger has the SSR FOID item
未定义，默认使用系统模板=Undefined, using System default template
不含证件号码的乘机人姓名或酒店入住人姓名=Name of passenger who is a boarding person or a checking in person with no ID number.
投保短信=Insurance buying
酒店电话=Hotel Phone number
接收号码=Recipient telephone
入库之后的PNR请不要进行修改。=Please do not modify the PNR after warehousing.
在财务收银完成并给会员产生积分后，系统自动发送积分生效通知给会员。=After the financial cashier completes and generates the points to the member, the system automatically sends the notice to the member that points are effective.
请不要导入已经出票、假RR或者输入过FP/FN/FC/EI项目的PNR。=Do not import a PNR that has already been ticketed, fake RRs, or entered the FP/FN/FC/EI items.
发送方式=Send mode
如需预订返程 机票或酒店，请拨打=If you need to book a return ticket or hotel, please call
失败短信=Failed
使用日期（明细）=Use Date (detail)
新增显示状态，编辑为显示状态则在调度中心->发送短信->更多短信模版列表显示。=Add new display status, edit the display status in the dispatch center-> Send SMS-> More SMS Template list display.
预付款支付密码=Prepayment Payment Password
在线充值短信=On-line Recharge SMS
常旅客出票=Frequent Flyer Tickets
待发短信=Waiting
样式二（仅适用于国际）=Style 2 (International only)
如：广州-长沙11月25日10：00起飞CZ3376航班=Example: Guangzhou-Changsha, November 25 10 :00am depart, flight CZ3376
中文/拼音/机场代码=Chinese/pinyin/airport code
使用说明=Tips
样式五（仅适用于国际）=Style V (International only)
输入时必须注意大小写=Attention! Case sensitive!
样式三（可调节边距字号）=Style 3 (adjustable margin font size)
会员自行在网上预订机票后系统自动发送订座内容，订座员后台订座仍需使用DX指令发送=The system automatically sends the contents of the booking after members booking tickets online on their own, booking seat in the background still need to use the DX instruction.
打印预览=Print Preview
号码必须按格式输入：手机：13812345678，小灵通：02032053210；=The number must be entered in format: Mobile: 13812345678, PHS: 02032053210;
提示：接受短信的号码只能填写数字和逗号（半角），支持小灵通发送。=Tip: Use commas (half-corner) to separate different telephone number, support PHS send.
选择政策成功=Successfully Select Policy
会员积分=Member points
发送时间=Send time
提示：只有在小太阳里面进行 票证管理并且已使用的行程单号才能作废=Tip: Void operation is only valid in Skyecho system with used itinerary.
入住房型=Occupancy type
航班延误=Flight delays
短信内容=Content
元RMB=RMB
其他税费=Other taxes
机票预订=Airline booking
换=Switch
礼品验证=Gift Verification
暂时预警=Temporary alerts
总积分=Total points
如：广州-长沙11月25日1000起飞1110抵达CZ3376航班=Example: Guangzhou-Changsha November 25 10:00am depart ,11:10am arrival, flight CZ3376
短信统计=SMS Statistics
支持中国移动、中国联通、中国网通手机用户和电信小灵通用户。=Support China Mobile, China Unicom, China Netcom mobile phone users and China Telecom PHS users.
贵公司必须先定义自定义短信模板，并且给相应操作人员开通短信权限后，系统才会发送相应短信。=Your company must first define a customized SMS template, and authorize operators the SMS permissions, the system will send the corresponding SMS.
机场 取票地址及电话信息=Airport pickup address and telephone number
分组名称=Groups
获取密码=Get password
样式四（发送电子行程单）=Style IV (send e-itinerary)
请输入作废行程单号：=Please enter the void itinerary number:
如果您的编码不是我们平台系统的订座的，请在编码里输入指令授权我们提取编码内容:RMK TJ AUTH=If your PNR is not the booking of our platform, please enter the directive in the PNR to authorize us to  extract the PNR content: RMK TJ AUTH
含票号的乘机人姓名=Name of passenger with ticket number
温馨提示：=Tips:
含证件号码不带括号的乘机人姓名=Name of person with ID number without brackets
条短信可发送=Message can be sent
短信类型=SMS Type
条数=SMS(s)
会员姓名=Member name
系统模板=Templates
短信通配符使用说明=SMS Wildcard Description
改签报表=Exchange Report
支付宝出票=Alipay ticket
代金券=Vouchers
请输入预付款支付密码=Please enter the prepayment payment password
旅游预订=Travel reservations
签注=Endorsement
请确认PNR的姓名、舱位、航段组正确，请确认舱位状况。=Please make sure the PNR's name, cabin, and the flight section correct, please confirm the status of cabin.
正在执行出票指令操作，请稍等=Ticketing now, please wait a moment
天气预报=Weather forecast
定时发送=Send later
请您核对：乘机人。=Please check: passenger.
登录口令=Login Password
如：CZ3376/11月25日/广州白云国际机场10:00T2航站楼-长沙黄花机场11:10=Example: CZ3376/November 25/Guangzhou Baiyun International Airport 10:00 T2 Terminal-Changsha Huanghua Airport 11:10
一次性发送超过10个（含）以上手机号码时。系统将自动将短信切换到定时短信通道进行发送。=Send more than 10 (including 10) telephone numbers at one time. The system will automatically switch SMS to a timed SMS channel for sending.
录入日期（汇总）=Entry Date (rollup)
添加模版=Add Template
燃油附加费=Fuel Fee
立即发送=Send Now
乘客超出儿童（2-12岁）年龄范围=Not a child!(Child’s age: 2-12 years old)
酒店最晚到达时间=Arrival time limit of the hotel
机场大巴时刻表（抵达城市）=Airport shuttle Bus Timetable (arrival in the city)
手动填写号码时每次最多允许输入号码100个，发送多个号码以空格“”或英文逗号“,”隔开；=You can fill in at most 100 different telephone numbers manually each time, Use commas (half-corner) or space to separate different telephone number;
测试短信=Test SMS
上边距=Top margin
配送提醒短信=Delivery Reminder
会员自行在网上或订座员后台预订酒店后系统自动发送订房内容=The system sends the hotel booking details to members no matter how the booking is made.
群发短信=Bulk SMS
挂机短信=Hang up
发送对象=Send to
机场大巴时刻表（出发城市）=Airport bus Timetable (departure city)
会员在网上注册或后台注册成功后系统自动发送会员注册通知=Member registration notices will be sent automatically after the successful registration online or backstage.
酒店预订=Hotel Reservations
样式六（电子客票行程单）=Style 6 (e-ticket itinerary)
国际提醒=International reminders
样式七（客户机票欠款单）=Style 7 (Customer tickets arrears)
短信列表=SMS List
公司网址=Company website
常旅客订座=Frequent Flyer Booking
发送统计=Send statistics
自动=Yes
行程单查询=Itinerary Enquiry
点这里返回上一页=Back to previous page
系统自动获取PNR内容	System automatically acquires PNR content=
左边距=Left margin
已完成审核代打票号=Completed
已发短信=Sent
样式八（退废单退废票办理单）=Style 8 (Reissue&Refund processing)
消费积分=Bonus points
国内机票预订单=Ticket Order
短消息字数计算办法:一个中文字或英文字（含字母、数字、标点、空格）均按1个字计算。手机64个字/条，小灵通45个字/条；=SMS character counting method: One Chinese/English character (including letters, numerals, punctuation, spaces) is calculated as 1 word. Telephone:64 words/SMS, PHS:45 words/SMS;
时间范围=Time range
密码修改验=Password modifications
生日祝福=Birthday Blessings
订房数量=Number of reservations
酒店名称=Hotel Name
全部选中=Select All
Offiic号=OFFIIC No.
自动发送=Auto Send
重写=Clear
作废行程单=void itinerary
有效身份证件号码=Valid ID number
如：广州-长沙11月25日周五1000起飞CZ3376航班=Example: Guangzhou-Changsha November 25 Friday 10:00am dapart, flight CZ3376
出票短信=Ticketing Message
配送员手机=Delivery Staff telephone number
发送序号=Send order
订座短信=Booking status
回执=Answer
酒店预订入住日期=Date of checking in
打印退改签规定	Print Reissue&Refund rules=
机场建设费=Airport Fee
本地=Local
贵公司还剩下=Your company has remained
预付款出票=Advance Payment ticket
入住酒店夜数=Staying
显示状态=Display status
预付款验证=Prepayment verification
发送者=Sent by
今天=Today
由系统判断，根据业务需要自动匹配短信模板并进行发送。=Depending on system, based on different business needs then automatically match SMS template and send.
预付款扣款=Prepayment deduction
配送员=Delivery Staff
酒店地址=Hotel Address
客户预付款=Customer Prepayment
获取政策失败=Failed to get policy
客户热线=Customer Hotline
酒店确认=Hotel Confirmation
资金账户=Funds
分配下级分销账号数量总共(与上条合并)=sub-distributor used
订单信息=Order Information
技术支持=Technical support
当前分销总共授权账号数量=Total usable account(s)
LOGO显示=Logo display
保险销售=Insurance Sales
上传新LOGO=Upload new logo
验证登登录密码=Verify Login Password
标记为*的为必填项=“*” item MUST NOT be empty
填写QQ号码=Enter your QQ
以内=within
剩余可分配账号=remain
图片尺寸最好控制在=Recommended picture size
LOGO地址=Logo address
宽=Width
高=Height
给您带来的不便敬请谅解=thanks for you understanding
登录密码不正确=Incorrect login password
大小不要超过=File size limit
我们在线支付时间为=Online payment time is
请选择上传图片=Please select picture
请输入登录密码=Please enter your login password
被暂用=operator(s) being suspended 
定期更换您的密码可以可以让您的账户更加安全。=Replacing your password periodically can make your account safer.
密码必须是6位以上8位以下的数字或字母=Password should be 6 to 8 numbers or characters. 	
投诉电话=Hotline
处理对象=Object
我已阅读同意《网络电子客票协议》=I have read <online electronic ticket agreement>
机票退废=Refund
旅客自愿退票=Voluntary refund of passengers
因航空公司或机场原因要求劝退的，请在此上传全退证明。=Due to the airline or airport reasons for full refund, please upload full refund proof.
同意以上条款，去核对=Agreed and Check
无手续费=No commission
延误/病退证明=Delay/Sickness Proof
航站费=Terminal fee
非自愿降舱=Involuntary descending Cabin
名字错换开重出=Change ticket due to wrong name.
选择银行（个人）=Select Bank (individual)
客人自愿退票=Refund
申请全退=Apply for full refund
PATA运价信息提取失败，请稍后重试=PATA failed, please try again later
按实际情况选择退废票的类型=Choose the type of refund according to the actual situation
当日废票=The first day only
上传的文件类型不符合要求=Uploaded file type is not supported.
团队签证无法单独购买机票，详情请咨询签证办理方=Team Visa can not purchase tickets separately, please consult the visa issuer for details
本地出票支付金额=Local Invoice Payment
支付票款金额=Payment Amount
提交退票之前，请先取消座位，解挂客票，并作废行程单！=Before refund, please cancel the seat, free pending ticket, and void the itinerary.
订座成功，订座记录编号为=Booking seats done! PNR is 
改期升舱=Reschedule&Upgrade
重复购票=Repeatedly purchase
航空公司拒载=Airline refuse the passenger
请严格按照等级时所用证件上的信息填写=Please make sure that fill in ID info is strictly equal as boarding ID info.
正常改期费是保存到税金字段，加收的改期费和升舱费保存到票价字段，这样才能和TSL报表对应。=The normal reschedule fee is saved to the Tax field,extra reschedule and upgrade fee are saved to the ticket field ,so that the TSL report corresponds.
病退及陪同=Sick passenger
有病退证明=With proof
选择客户、乘机人=Choose passenger
非自愿=Involuntary
机票须按航班起飞时间顺序使用，否则无法登机=Tickets must be used in order of departure time, otherwise passengers can not board.
本客规仅供参考，如果有误请及时联系我们更改=This is only for your reference, If there is any problem,please contact us
正常退票=Normal refund
服务等级=Service level
您可点击下方标题进行排序=Click a title to order results
一键删除所有政策=Delete All Policies
城市中文名=City(Chinese)
系统内提供的基本票价仅供参考，实际执行票价以民航系统内发布为准。=The basic fare provided in the system is only for reference, please check the airline notice for actual fare.
英文名称=City(English)
车站=Stop
显示格式=Format
始发销售政策=Origin Sales Policy
国家=Country
政策期限=Policy Validity
所属国家=Country
始发城市=Depart from
直升机场=Heliport
中文名称=City(Chinese)
城市区号=City Code
时差=Time difference
机场英文名=Airport(English)
军用机场=Military airport
三字码类型=3 letters code type
散客=Individual
城市三字码与机场三字码重合=The city and airport share the same 3 letters code
区号=Area code
行程=Type
火车站=Railway station
城市三字码=City
州省=State(Province)
飞行距离=Distant
机场中文名=Airport(Chinese)
航空公司选择=Airline 
有效日期=Valid date
请输入查询关键字=Keyword
所有航空公司=All
普通航班=Normal Flight
基本票价=Fare
码头=Dock
空军基地=Air Base
今日更新=Newly updated
重新搜索=Search
政策类型=Policy Type
基础折扣率=Base Rate
三字码=3 letters code
点数大小=Minimum Rate
联程航班=Connecting Flight
城市英文名=City(English)
推荐=Recommended
有效政策=Effective one(s)
城市类型=City type
机场三字码=Airport
数据下载=Download
保险公司=Company
位数字i=Digit I
分销商=Distributor
销售=Sales
申请被拒绝=Application is rejected
订单来源=Ordered by
投保=Insure
待退保=Pending surrender
按订单来源统计=Order Source
保单号=Policy number
必填项=is required
投退人=Insure/Surrender
下一步，去支付=Go to Pay
按分销统计=Distributor
在线投保=Online
生效日期=Valid Date
已退保=Surrender
投保机构=Agencies
流水号=Serial number
保险产品名称=Product name
按中心、产品类型统计=Center, Product type
移动APP=Mobile app
保险采购=Purchase
投退日期=Valid Date
投保日期=Insured Date
按分销商、产品类型统计=Distributor, Product type
请输入 登录密码=Please enter login password
保险产品=Products
差旅=Travel
异常单数量=Abnormal orders
结算总计=Settlement totals
保单查询=Orders
退保=Surrender
按投保人/退保人统计=Applicant/Surrender
贵公司还剩下0条短信可发送（参考页面）=Your company still leaves 0 SMS to send (Reference page)
被保人=Insured
同行总计=Peer(s)
已投保=Insured
投退时间=Surrender time
保险状态=Insurance status
微信=WeChat
投保状态=Insured status
异常订单=Abnormal order
网站=Website
退保日期=Surrender Date
邮编=邮编
不能查看销售政策=不能查看销售政策
发布方=发布方
特价机票联系人=特价机票联系人
本地预留=本地预留
文件失败=文件失败
抵达城市不能为空=抵达城市不能为空
传真=传真
生成=生成
停用政策=停用政策
本部政策=本部政策
请选择要=请选择要
下载完毕时请点击下面的=下载完毕时请点击下面的
的政策=的政策
已审=已审
修改政策=修改政策
你确定要删除所有政策吗=你确定要删除所有政策吗
全额返佣=全额返佣
始发=始发
回程期限=回程期限
启用政策=启用政策
请检查查看政策期限终止日期输入是否正确=请检查查看政策期限终止日期输入是否正确
贵公司的返佣政策尚未设定=贵公司的返佣政策尚未设定
请检查查看政策期限开始日期=请检查查看政策期限开始日期
请检查有效日期输入是否正确=请检查有效日期输入是否正确
除外出发=除外出发
按钮来删除服务器上的文件=按钮来删除服务器上的文件
批量启用=批量启用
供应商资料=供应商资料
易行=易行
批量停用=批量停用
政策下载=政策下载
除外抵达=除外抵达
发布人=发布人
自=自
批量修改选中的政策=批量修改选中的政策
出票期限=出票期限
敬告=敬告
定额=定额
下载地址=下载地址
请确认是否删除该数据=请确认是否删除该数据
维护日期=维护日期
出发城市不能为空=出发城市不能为空
班期=班期
删除政策=删除政策
外部政策=外部政策
所有=所有
点数大于=点数大于
为了你的数据安全=为了你的数据安全
数据=数据
批量删除选中的政策=批量删除选中的政策
超放=超放
文件成功=文件成功
修改政策点数=修改政策点数
返佣方式=返佣方式
请联系系统管理中心开通权限=请联系系统管理中心开通权限
返程=返程
我的政策=我的政策
外部政策由于数据量大=外部政策由于数据量大
位整数或=位整数或
按照规则返佣=按照规则返佣
不能打开文件=不能打开文件
内部=内部
已停用=已停用
请输入出发城市=请输入出发城市
停用=停用
请检查查看政策期限开始日期输入是否正确=请检查查看政策期限开始日期输入是否正确
位小数=位小数
请保留整数或两位小数且不能大于=请保留整数或两位小数且不能大于
批量启用选中的政策=批量启用选中的政策
同行政策=同行政策
低=低
航空政策=航空政策
审核政策=审核政策
适用舱位=适用舱位
单去及往返=单去及往返
批量停用选中的政策=批量停用选中的政策
请确认是否批量=请确认是否批量
未审=未审
全部政策=全部政策
网址=网址
请输入抵达城市=请输入抵达城市
下载政策=下载政策
政策归属=政策归属
政策来源=政策来源
行程类型=行程类型
打印失败=打印失败
编码获取失败=编码获取失败
不得签转变更退票=不得签转变更退票
订座记录不存在=订座记录不存在
行程单号获取失败=行程单号获取失败
直接打印=直接打印
请检查电子客票号码位数是否正确=请检查电子客票号码位数是否正确
数据获取失败=数据获取失败
请检查订座记录位数是否正确=请检查订座记录位数是否正确
不得更改不得签转不得退票=不得更改不得签转不得退票
查询不到有效行程单号=查询不到有效行程单号
电子客票号码不存在=电子客票号码不存在
查询不到有效的行程单号=查询不到有效的行程单号
您的浏览器不支持XHR对象=您的浏览器不支持XHR对象
不得签转不得退票=不得签转不得退票
不得签转=不得签转
请检查要打印的行程单=请检查要打印的行程单
不得签转仅限原出票地退票=不得签转仅限原出票地退票
不得变更不得签转=不得变更不得签转
电子客票号码获取失败=电子客票号码获取失败
订单处理=Orders
国际机票预订=International
退废改票管理=Refund&Reissue
乘机人重复,请检查乘机人信息=乘机人重复,请检查乘机人信息=Take the opportunity to repeat, please check the flight information
时刻=Time
最低舱位=Low
此处查询的价格仅供参考，实际价格以订单支付页面为准=此处查询的价格仅供参考，实际价格以订单支付页面为准
请准确填写登记人信息，以免影响正常登机=Attention！WRONG info affect boarding！
已支付,待出票=Paid&Wait
入库之后的PNR,请不要再进行修改。=After storage PNR, please don't make any changes.
请确认每个旅客均已输入证件号码 SSR FOID项。=Please confirm that each passenger has ID number SSR FOID item. 
请确保PNR内容真实准确，虚假PNR出票方有权拒绝出票。=Please make sure that PNR is true and accurate，otherwise the issuer has the right to refuse Ticketing. 
请确认PNR的姓名、舱位、航段组正确，请确认舱位状况。=Please confirm that Name、Cabin、Segment items in PNR are correct，please confirm the status of the cabin. 
请不要导入已经出票、假RR或者输入过 FP/FN/FC/EI 项目的PNR。=Cannot import the PNR which has already ticketed or contained false RR or entered FP/FN/FC/EI items. 
币种=Currency
确认以上改期信息无误=Confirm that the above information is correct 
中心已设置基准货币=中心已设置基准货币
汇率为=Exchange rate as
分销必须设置结算货币与汇率=Distributor must set Currency code and Exchange rate
汇率必须大于0=Exchange rate bigger than 0
请正确输入联系手机号码=Please enter your mobile number correctly
货币代码不能为空=Currency code cannot be empty
汇率不能为空=Exchange rate  cannot be empty
九元航空只能预定单程=AQ Airline company One way only 
春秋航空只能预定单程=9C Airline company One way only 
此航班的特价舱位已停止销售=The sale of this flight has been stopped
特价舱位已销售完毕,无法继续操作=The special shipping space has been sold out and can not continue operation  
舱的预订=Cabin book
没有有效的乘客资料=There is no valid passenger information
订单写入失败=Write to order failed 
该舱位没有位置=The berth has no seat 
预订不成功=Book unsuccessful
请选择有效的出发航班进行预订=Please select a valid departure flight for booking
请输入第=请输入第
位乘机人姓名=位乘机人姓名
位乘机人姓名不正确=位乘机人姓名不正确
九元航空订单需要提供旅客的出生日期=AQ air order will require the date of birth of the passenger 
乘客超出婴儿15日-2周岁的年龄范围=Passengers exceed the age range of 15 -2 years of age for infants 
位乘机人联系手机=位乘机人联系手机
成人和儿童不能一起预订=Adults and children cannot book together 
婴儿数不能大于成人数=The number of infants should not be greater than the adult population 
请输入联系人姓名=Please enter your contact name 
请选择省份=Please select the provinces 
请选择市/县=Please select the city / county 
请输入详细地址=Please enter a detailed address 
请输入邮政编码=Please enter the zip code 
必须同意机票预订条款才能进行下一步=You must agree to the terms of the ticket before you proceed to the next step 
确认使用新价格=Confirm the new price 
不使用新价格,取消订单=Cancel order
编码内容解析失败,请联系系统管理员=The code content analysis failed. Please contact the system administrator
儿童暂时不能导入=Children can not be imported for the time being 
成人、儿童、婴儿不能在同一个编码导入=Adults, children, and infants cannot be imported in the same PNR
生成订单失败=Write date error
价格更新失败=Price update failed 
价格更新成功,页面跳转中,请稍候=Price update successful, page Jump, please wait 
处理结果=Treatment result
查看人=View operator
预订CID=Book CID
QUEUE信箱=QUEUE mailbox
查看时间=View time
客户CID=Customer
生成Excel文件成功=Generate Excel file successfully
工作号=Work ID 
出票CID=Ticketing CID
删除文件=Delete file
只允许查询跨度15天以内的数据=Queries are allowed only within 15 days of the data
否则后果自负=Otherwise, the consequences
获取时间=Gettime
QUEUE内容=QUEUE content
QUEUE信息=QUEUE information
已用结算税金=Used tax
已用结算机场税=Airport tax
已用结算燃油税=used fuel tax
民航指令=Civil aviation directive
其它权限=Other permissions
士兵证=Soldier
应收小计=subtotal
退款大于订单应收=A refund is greater than an order receivable
已选航段少于总航段数=The selected segment is less than the total number of sectors 
是否关联订单号=Would you like to be associate with other order number?